<?php

/**
 * 我的奖品
 * */
class Controller_Prize extends \Base
{

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }

    /**
     * 奖品列表
     * */
    public function listAction()
    {
        $this->display();
    }

}