<?php

/**
 * Description of Domain
 *
 * @author Sgenmi
 * @date 2017-6-29
 * @Email 150560159@qq.com
 */
class Domain {

    private static $domain = array(
        'com' => array(
            'google' => 1, 'ip138' => 1, 'wahtismyip' => 1, '4shared' => 1, 'gloryhole' => 1,
            'dogfartnetwork' => 1, 'mingpaovan' => 1, 'passion' => 1, 'freechal' => 1, 'mail-archive' => 1,
            'admob' => 1, 'zkiz' => 1, 'casinoriva' => 1, 'sadistic-v' => 1, 'directcreative' => 1,
            'vpnsp' => 1, 'ftchinese' => 1, 'nyt' => 1, 'stepmania' => 1, 'cmule' => 1, 'getgom' => 1, 'rapidvpn' => 1,
            'robtex' => 1, 'thelifeyoucansave' => 1, 'ugo' => 1, 'looktoronto' => 1, 'amoiist' => 1,
            'zillionk' => 1, 'placemix' => 1, 'bookepub' => 1, 'twitstat' => 1, 'thinkingtaiwan' => 1,
            'tiananmenuniv' => 1, 'freemorenews' => 1, 'mesotw' => 1, 'flipkart' => 1, 'firstfivefollowers' => 1,
            'beyondfirewall' => 1, 'xanga' => 1, 'ontrac' => 1, 'dalailama' => 1, 'gtricks' => 1, 'fizzik' => 1,
            'aniscartujo' => 1, 'imlive' => 1, 'motherless' => 1, 'bigfools' => 1,
            'ziplib' => 1, 'googlesource' => 1, 'makemymood' => 1, 'huhamhire' => 1, 'juliereyc' => 1, '5i01' => 1,
            'anysex' => 1, 'provideocoalition' => 1, 'beijingspring' => 1, 'twiffo' => 1, 'blinkx' => 1, 'thaicn' => 1,
            'michaelmarketl' => 1, 'acgkj' => 1, 'branch' => 1, 'soupofmedia' => 1, 'strongwindpress' => 1, 'html5rocks' => 1,
            'uptodown' => 1, 'po2b' => 1, 'nzchinese' => 1, 'viu' => 1, 'bloombergview' => 1, 'highpeakspureearth' => 1,
            'twitonmsn' => 1, 'chromecast' => 1, '5maodang' => 1, 'idouga' => 1, 'fevernet' => 1, 'peacehall' => 1, 'rdio' => 1, 'pure18' => 1,
            'fc2web' => 1, 'matome-plus' => 1, 'lagranepoca' => 1, 'listentoyoutube' => 1, 'banana-vpn' => 1, '1mobile' => 1,
            'sokamonline' => 1, 'hulu' => 1, 'busytrade' => 1, 'twiyia' => 1, 'monster' => 1, 'dupola' => 1,
            'coolaler' => 1, 'ngensis' => 1, 'memorybbs' => 1, 'd2bay' => 1, 'twitterrific' => 1, 'novelasia' => 1, 'zfreet' => 1, 'idreamx' => 1, 'mgstage' => 1, 'rssmeme' => 1, 'wsj' => 1,
            'googleblog' => 1, 'lsmwebcast' => 1, 'asahichinese' => 1, 'twicsy' => 1, 'sweux' => 1, 'wikileaks-forum' => 1,
            'wefong' => 1, 'astrill' => 1, 'livingstream' => 1, 'telegramdownload' => 1, 'meshrep' => 1, 'twilightsex' => 1, 'stephaniered' => 1,
            'hybrid-analysis' => 1, 'martinoei' => 1, 'dxiong' => 1, 'zannel' => 1, 'muzi' => 1, 'tokyocn' => 1, 'linpie' => 1, 'fc2' => 1,
            'bnrmetal' => 1, 'entnt' => 1, 'speakerdeck' => 1, 'chatnook' => 1, 'kusocity' => 1, 'twttr' => 1, 'backchina' => 1, 'newstamago' => 1, 'thespeeder' => 1,
            'chapm25' => 1, 'urlparser' => 1, 'gvt0' => 1, 'betfair' => 1, 'oursogo' => 1, 'jamyangnorbu' => 1, 'ccue' => 1, 'dajiyuan' => 1,
            'youmaker' => 1, 'anonymizer' => 1, 'finchvpn' => 1, 'nuvid' => 1, 'syx86' => 1, 'gokbayrak' => 1, 'wow' => 1, 'falsefire' => 1, 'v2ex' => 1,
            'traffichaus' => 1, 'cartoonmovement' => 1, 'cnineu' => 1, 'pullfolio' => 1, 'bgvpn' => 1, 'yousendit' => 1, 'proxpn' => 1, 'pornsharing' => 1,
            'david-kilgour' => 1, 'javzoo' => 1, 'shat-tibet' => 1, 'newsdh' => 1, 'fux' => 1, 'asianfreeforum' => 1, 'cacnw' => 1, 'karkhung' => 1,
            'pbworks' => 1, 'tibethaus' => 1, 'freerk' => 1, 'networkedblogs' => 1, 'cumlouder' => 1,
            'bailandaily' => 1, 'coolder' => 1, 'myfreshnet' => 1, 'netbirds' => 1, 'proyectoclubes' => 1, 'vegasred' => 1,
            'e-gold' => 1, 'penisbot' => 1, 'jitouch' => 1, 'youtubecn' => 1, 'himalayanglacier' => 1, 'gelbooru' => 1, 'fringenetwork' => 1, 'spinejs' => 1,
            'tvants' => 1, 'raggedbanner' => 1, 'tiney' => 1, 'iyouport' => 1, 'msn' => 1, 'ifanqiang' => 1, 'eisbb' => 1, 'voacantonese' => 1, 'bbsone' => 1,
            'twisterio' => 1, 'page2rss' => 1, 'morbell' => 1, 'bbsmo' => 1, 'footwiball' => 1, 'tinypaste' => 1, 'ecstart' => 1, 'googleartproject' => 1, 'megarotic' => 1,
            'tweetrans' => 1, 'mediafire' => 1, 'globalmediaoutreach' => 1, 'goldbet' => 1, 'blogs' => 1, 'chromeadblock' => 1, 'bestvpnserver' => 1, 'njuice' => 1,
            'search' => 1, 'hkhkhk' => 1, 'puffstore' => 1, 'advanscene' => 1, 'miroguide' => 1, 'cool18' => 1, 'ninjacloak' => 1, 'dw-world' => 1,
            'fangbinxing' => 1, 'janwongphoto' => 1, 'venchina' => 1, 'meetup' => 1, 'thedalailamamovie' => 1, 'gamejolt' => 1, 'photofocus' => 1, 'qmzdd' => 1,
            'foxbusiness' => 1, 'javhuge' => 1, 'diigo' => 1, 'rightster' => 1, 'twitterkr' => 1, 'anontext' => 1, 'playboyplus' => 1, 'fulue' => 1,
            'turningtorso' => 1, 'ladbrokes' => 1, 'mk5000' => 1, 'americangreencard' => 1, 'incloak' => 1, 'behindkink' => 1, 'vporn' => 1, '50webs' => 1,
            'vtunnel' => 1, 'bestvpn' => 1, 'nakido' => 1, 'economist' => 1, 'xiezhua' => 1, 'box' => 1, 'rileyguide' => 1, 'twitgoo' => 1,
            'facesofnyfw' => 1, 'echofon' => 1, 'pdetails' => 1, 'stgloballink' => 1, 'iuksky' => 1, 'fbsbx' => 1, 'feministteacher' => 1, 'slinkset' => 1,
            'chinaxchina' => 1, 'chinasocialdemocraticparty' => 1, 'doujincafe' => 1, 'financetwitter' => 1, 'nextmedia' => 1, 'earlytibet' => 1, 'relaxbbs' => 1, 'calameo' => 1, 'wattpad' => 1, '666kb' => 1,
            'cnn' => 1, 'nytimes' => 1, 'summify' => 1, 'radiotime' => 1, '17t17p' => 1, 'retweetist' => 1, 'dessci' => 1, 'gstatic' => 1,
            'brizzly' => 1, 'wallpapercasa' => 1, 'ka-wai' => 1, '2lipstube' => 1, 'sugobbs' => 1, 'bettervpn' => 1, 'fxnetworks' => 1, 'bizhat' => 1,
            'sogclub' => 1, 'vpnreviewz' => 1, 'qtweeter' => 1, 'sciencenets' => 1, 'chicagoncmtv' => 1, 'eriversoft' => 1, 'hrcir' => 1, 'emule-ed2k' => 1, 'alabout' => 1, 'viber' => 1,
            'mmaaxx' => 1, 's4miniarchive' => 1, 'netfirms' => 1, 'vevo' => 1, 'hoovers' => 1, 'googlehosted' => 1, 'broadbook' => 1, 'goldwave' => 1,
            'polymerhk' => 1, 'myactimes' => 1, 'onlineyoutube' => 1, 'i-cable' => 1, 'etokki' => 1, 'boyfriendtv' => 1, 'wdf5' => 1, 'iicns' => 1,
            'foolsmountain' => 1, 'torrentcrazy' => 1, 'scmp' => 1, 'zozotown' => 1, 'lsmradio' => 1, 'shopping' => 1, 'medium' => 1, 'wp' => 1,
            'matainja' => 1, 'glype' => 1, 'a-normal-day' => 1, 'apetube' => 1, 'biantailajiao' => 1, 'assembla' => 1, 'chrdnet' => 1, 'tube' => 1,
            'philly' => 1, 'psiphon3' => 1, 'icams' => 1, 'mingpaonews' => 1, 'gopetition' => 1, 'gongwt' => 1, 'fooooo' => 1, 'twilio' => 1,
            'in' => 1, 'vidoemo' => 1, 'tibetalk' => 1, 'taiwanbible' => 1, 'htmldog' => 1, 'mimivip' => 1, 'porntvblog' => 1, 'yilubbs' => 1, 'nokola' => 1, 'badjojo' => 1,
            'extmatrix' => 1, 'luke54' => 1, 'fan-qiang' => 1, 'javmoo' => 1, 'gotrusted' => 1, 'chinainperspective' => 1, 'tibetcity' => 1, 'lookpic' => 1, 'mingpaocanada' => 1,
            'fleursdeslettres' => 1, 'urbanoutfitters' => 1, '3arabtv' => 1, 'homeperversion' => 1, 'c-est-simple' => 1, 'dalailamahindi' => 1, 'vpnreactor' => 1, 'thevivekspot' => 1, 'yibaochina' => 1,
            'mingpaomonthly' => 1, 'foxgay' => 1, 'fileforum' => 1, 'tunnelbear' => 1, 'zgsddh' => 1, '21pron' => 1, 'cristyli' => 1, 'easypic' => 1, 'urlborg' => 1, 'googlesile' => 1,
            'bonbonme' => 1, 'hkepc' => 1, 'entermap' => 1, 'theinitium' => 1, 'pdproxy' => 1, 'huffingtonpost' => 1, 'flightcaster' => 1, '10conditionsoflove' => 1, 'reuters' => 1, 'vpnmaster' => 1,
            'cn' => array(
                'unblock' => 1,
            ),
            'beevpn' => 1, 'whereiswerner' => 1, 'sugarsync' => 1, 'nuzcom' => 1, '3a5a' => 1, 'helloqueer' => 1, 'baby-kingdom' => 1, 'tube8' => 1, 'dotplane' => 1,
            'vansky' => 1, 'proxfree' => 1, 'tvunetworks' => 1, 'akiba-online' => 1, 'target' => 1, 'adult-sex-games' => 1, 'alphaporno' => 1, 'moroneta' => 1, 'kcoolonline' => 1, 'cyberghostvpn' => 1,
            'billywr' => 1, 'toodoc' => 1, 'tangben' => 1, 'yam' => 1, 'porn' => 1, 'yidio' => 1, 'plus28' => 1, 'picasaweb' => 1, 'vpnhq' => 1, 'newcenturymc' => 1,
            'newcenturynews' => 1, 'newsminer' => 1, 'koranmandarin' => 1, 'cam4' => 1, 'socialwhale' => 1, 'meripet' => 1, 'yeahteentube' => 1, 'drtuber' => 1,
            'kebrum' => 1, 'thinkwithgoogle' => 1, 'ziddu' => 1, 'tumblr' => 1, 'tv' => 1, 'securitykiss' => 1, 'betvictor' => 1, 'alien-ufos' => 1, 'breakingtweets' => 1, 'informer' => 1, 'secretchina' => 1,
            'talkboxapp' => 1, 'gradconnection' => 1, 'ismaelan' => 1, 'blacklogic' => 1, 'scmpchinese' => 1, 'bebo' => 1, 'weiboleak' => 1, 'osfoora' => 1, 'mingpaony' => 1, 'chinatweeps' => 1,
            'songjianjun' => 1, 'slickvpn' => 1, 'chinesedaily' => 1, 'mizzmona' => 1, 'helplinfen' => 1, 'imagefap' => 1, 'sfshibao' => 1, 'megurineluka' => 1, 'iverycd' => 1, 'jdwsy' => 1,
            'uu-gg' => 1, 'liudejun' => 1, 'fanswong' => 1, 'van001' => 1,
            'sa' => array(
                'china-mmm' => 1,
            ),
            'boxun' => 1, 'pacopacomama' => 1, 'gotgeeks' => 1, 'oizoblog' => 1, 'apigee' => 1, 'roodo' => 1, 'putlocker' => 1, 'eevpn' => 1,
            'dafagood' => 1, 'sinocast' => 1, 'commentshk' => 1, 'opera' => 1, 'mpfinance' => 1, 'pornvisit' => 1, '7cow' => 1, 'slavasoft' => 1, 'slacker' => 1, 'moonbbs' => 1,
            'gyatsostudio' => 1, 'nbc' => 1, 'mimivv' => 1, 'googleplus' => 1, 'abchinese' => 1, 'paldengyal' => 1, 'thegly' => 1, 'epochtimes-romania' => 1, 'padmanet' => 1, 'dotsub' => 1,
            'yanghengjun' => 1, 'mathiew-badimon' => 1, 'lastcombat' => 1, 'tiananmenduizhi' => 1, 'cdninstagram' => 1, 'visibletweets' => 1, 'gluckman' => 1, 'brutaltgp' => 1,
            'keepandshare' => 1, 'avoision' => 1, 'shinychan' => 1, 'yesasia' => 1, 'rocketbbs' => 1, 'afantibbs' => 1, 'network54' => 1, 'azerimix' => 1, 'liuhanyu' => 1,
            'vietdaikynguyen' => 1, 'live' => 1, 'ronjoneswriter' => 1, 'bbsfeed' => 1, 'mymaji' => 1, 'tubecao' => 1, 'dontmovetochina' => 1, 'hidemyass' => 1, 'myparagliding' => 1, 'pandora' => 1,
            'x365x' => 1, 'getcloudapp' => 1, 'aolnews' => 1, 'jigong1024' => 1, 'imagevenue' => 1, 'newstarnet' => 1, 'ebony-beauty' => 1, 'moodyz' => 1,
            'streetvoice' => 1, 'myeclipseide' => 1, 'grammaly' => 1, 'botanwang' => 1, 'edmontonservice' => 1, 'ucanews' => 1, 'dropbox' => 1, 'ipalter' => 1, 'isunaffairs' => 1, 's8forum' => 1,
            'netsneak' => 1, 'picturesocial' => 1, 888 => 1, 'offbeatchina' => 1, 'beaconevents' => 1, 'theblemish' => 1, 'casinoking' => 1, 'anthonycalzadilla' => 1,
            'jiangweiping' => 1, 'bartvpn' => 1, 'feelssh' => 1, 'boardreader' => 1, 'geocities' => 1, 'moeerolibrary' => 1, 'wuerkaixi' => 1, 'tnaflix' => 1, 'billypan' => 1, 'zvereff' => 1,
            'pastebin' => 1, 'i818hk' => 1, 'rmjdw' => 1, 'erodaizensyu' => 1, 'wetplace' => 1, 'hkpeanut' => 1, 'ccthere' => 1, 'tianlawoffice' => 1, 'slyip' => 1, 'goagentplus' => 1,
            'blackvpn' => 1, 'electionsmeter' => 1, 'phncdn' => 1, 'gfsale' => 1, 'blogcatalog' => 1, 'mysinablog' => 1, 'hwinfo' => 1, 'vpnfire' => 1, 'ovi' => 1, 'efukt' => 1,
            'tsemtulku' => 1, 'spb' => 1, 'vimeo' => 1, 'ninecommentaries' => 1, 'definebabe' => 1, 'xmovies' => 1, 'android' => 1, 'japan-whores' => 1, 'starp2p' => 1, 'dalailamaworld' => 1,
            'pbxes' => 1, 'getfreedur' => 1, 'sevenload' => 1, 'lockdown' => 1, 'idsam' => 1, 'metacafe' => 1, 'zaozon' => 1, 'zhangtianliang' => 1, 'peeasian' => 1, 'mixero' => 1,
            'imgmega' => 1, 'toutfr' => 1, 'tokyo-247' => 1, '21sextury' => 1, 'fileserve' => 1, 'tvboxnow' => 1, 'pandavpn-jp' => 1, 'feedburner' => 1, 'sex-11' => 1, 'twitturk' => 1,
            'fapdu' => 1, '32red' => 1, 'imdb' => 1, 'bt95' => 1, 'inoreader' => 1, 'hqjapanesesex' => 1, 'googledrive' => 1, 'israbox' => 1, 'prestige-av' => 1, 'libraryinformationtechnology' => 1,
            'alwaysdata' => 1, 'williamhill' => 1, 'expatshield' => 1, 'gardennetworks' => 1, 'waffle1999' => 1, 'savemedia' => 1, 'vpnpick' => 1, 'wwitv' => 1, 'storify' => 1, 'privatetunnel' => 1,
            'equinenow' => 1, 'thisav' => 1, 'apk-dl' => 1, 'hkreporter' => 1, 'fastssh' => 1, 'simpleproductivityblog' => 1, 'freexinwen' => 1, 'scriptspot' => 1, 'chenguangcheng' => 1, 'cdw' => 1,
            'devpn' => 1, 'mcreasite' => 1, 'heungkongdiscuss' => 1, 'ggssl' => 1, 'alljackpotscasino' => 1, 'sitekreator' => 1, 'china101' => 1, 'wenweipo' => 1, 'hideipvpn' => 1,
            'sina' => 1, 'gartlive' => 1, 'videopediaworld' => 1,
            'bcmorning' => 1, 'twittergadget' => 1, 'nytlog' => 1, 'dns2go' => 1, 'bitsnoop' => 1, 'xskywalker' => 1, 'procopytips' => 1, 'voagd' => 1, 'mingjingnews' => 1, 'iblist' => 1,
            'woeser' => 1, 'gamousa' => 1, 'hanunyi' => 1, 'tinychat' => 1, '9bis' => 1, 'qkshare' => 1, 'time' => 1, 'wiredpen' => 1, 'tripod' => 1,
            'jackjia' => 1, 'seevpn' => 1, 'wheelockslatin' => 1, 'zonaeuropa' => 1, 'xiaochuncnjp' => 1, 'ghostpath' => 1, 'club1069' => 1, 'mingpaosf' => 1,
            'heyzo' => 1, 'hihiforum' => 1, 'slheng' => 1, 'hustlercash' => 1, 'vanilla-jp' => 1, 'udn' => 1, 'pritunl' => 1, 'bloglines' => 1, 'laomiu' => 1,
            't66y' => 1, 'files2me' => 1, 'bestvpnservice' => 1, 'killwall' => 1, 'stormmediagroup' => 1, 'aiweiwei' => 1, 'twitvid' => 1, 'akiba-web' => 1, 'thebodyshop-usa' => 1, 'pornrapidshare' => 1,
            'apkdler' => 1, 'youtube' => 1, 'zhreader' => 1, 'jinpianwang' => 1, 'alwaysvpn' => 1, 'huangyiyu' => 1, '12bet' => 1,
            'beeg' => 1, 'edubridge' => 1, 'premeforwindows7' => 1, 'ezpeer' => 1, '2000fun' => 1, 'gettyimages' => 1, 'xcritic' => 1,
            'yzzk' => 1, 'tampabay' => 1, 'maskedip' => 1, 'nowtorrents' => 1, 'vanpeople' => 1, 'atlaspost' => 1, 'stickam' => 1, 'tuitwit' => 1,
            'fmnnow' => 1, 9001700 => 1, 'thetrotskymovie' => 1, 'kurtmunger' => 1, 'igvita' => 1, 'youshun12' => 1, 'xtube' => 1, 'hk-pub' => 1,
            'googlegroups' => 1, 'tablesgenerator' => 1, 'nurgo-software' => 1, 'byethost8' => 1, 'hustler' => 1, 'avcool' => 1, 'idiomconnection' => 1, 'dalailamafilm' => 1,
            'eyny' => 1, 'friendfeed' => 1, 'ozchinese' => 1, 'sohcradio' => 1, 'istockphoto' => 1, 'sinoants' => 1, 'goodreaders' => 1, 'lidecheng' => 1, 'epochtimes' => 1, 'mcfog' => 1,
            'new-akiba' => 1, 'lefora' => 1, 'gaeproxy' => 1, 'wisevid' => 1, 'zsrhao' => 1, 'bet365' => 1, 'power' => 1, 'boxunblog' => 1, 'fanqianghou' => 1, 'creadersnet' => 1, 'juziyue' => 1, 'ktzhk' => 1,
            '3boys2girls' => 1, '18onlygirls' => 1, 'unholyknight' => 1, 'cctongbao' => 1, 'sinocism' => 1, 'fileflyer' => 1, 'twitthat' => 1, 'ranyunfei' => 1, 'porn2' => 1, 'hyperrate' => 1,
            'ganges' => 1, 'ablwang' => 1, 'tweepmag' => 1, 'wuguoguang' => 1, 'ipvanish' => 1, 'bitshare' => 1, 'wsjhk' => 1, 'findmima' => 1, 'bonbonsex' => 1, 'homeservershow' => 1,
            'ibvpn' => 1, 'xiongpian' => 1, 'hiitch' => 1, 'lsxszzg' => 1, 'tmagazine' => 1, 'tycool' => 1, 'hotshame' => 1, 'skyhighpremium' => 1, 'hautelook' => 1,
            'stepchina' => 1, 'epochhk' => 1, 'alvinalexander' => 1, 'fingerdaily' => 1, 'fqrouter' => 1, 'cnproxy' => 1, 'duckmylife' => 1, 'twitter' => 1, 'lenwhite' => 1, 'kepard' => 1,
            'businessinsider' => 1, 'wnacg' => 1, 'getjetso' => 1, 'seesmic' => 1, 'warehouse333' => 1, 'casinobellini' => 1, 'sproutcore' => 1, 'freeones' => 1, 'getsmartlinks' => 1, 'fdbox' => 1,
            'aboluowang' => 1, 'kannewyork' => 1, 'mediafreakcity' => 1, 'boysfood' => 1, 'pornstarclub' => 1, 'enewstree' => 1, 'jqueryui' => 1, 'fzlm' => 1, 'mcadforums' => 1, 'freegao' => 1,
            'twibs' => 1, 'witnessleeteaching' => 1, 'chinagate' => 1, 'aol' => 1, 'canadameet' => 1, 'plusbb' => 1, 'freeyellow' => 1, 'tweetymail' => 1, 'sndcdn' => 1,
            'privatepaste' => 1, 'tibetsociety' => 1, 'xbabe' => 1, 'lalulalu' => 1, 'nuexpo' => 1, 'qanote' => 1, 'ssh91' => 1, 'lvv2' => 1,
            '4everproxy' => 1, 'twibbon' => 1, 'isuntv' => 1, 'tvider' => 1, 'caribbeancom' => 1, 'helpeachpeople' => 1, 'turbohide' => 1, '8-d' => 1,
            'skimtube' => 1, 'namsisi' => 1, 'redtube' => 1, 'goldbetsports' => 1, 'javseen' => 1, 'cloakpoint' => 1, 'jjgirls' => 1, 'msguancha' => 1,
            'mypopescu' => 1, 'heartyit' => 1, 'dw' => 1, 'taiwanyes' => 1, 'torrentprivacy' => 1, 'whatblocked' => 1, 'cotweet' => 1, 'liveleak' => 1,
            'tokyo-hot' => 1, 'qoos' => 1, 'anobii' => 1, 'thestandnews' => 1, 'tibetgermany' => 1, 'cachinese' => 1, 'fsurf' => 1, 'mingshengbao' => 1, 'ufreevpn' => 1,
            'hechaji' => 1, 'x-berry' => 1, 'nexon' => 1, 'cnet' => 1, 'zeutch' => 1, 'zhuatieba' => 1, 'phayul' => 1, 'webfreer' => 1, 'pagodabox' => 1, 'epochweek' => 1,
            'worldjournal' => 1, 'deaftone' => 1, '18virginsex' => 1, 'youporn' => 1, 'dayabook' => 1, 'dailidaili' => 1, 'mx981' => 1, 'powercx' => 1, 'matsushimakaede' => 1, 'duplicati' => 1,
            '141hongkong' => 1, '4irc' => 1, 'ippotv' => 1, 'peerpong' => 1, '7capture' => 1, 'civiliangunner' => 1, 'androidify' => 1, 'astonmartinnews' => 1, 'yymaya' => 1, 'javtag' => 1,
            'vivthomas' => 1, 'spankbang' => 1, 'here4news' => 1, 'fengzhenghu' => 1, 'taiwan-sex' => 1, 'expressvpn' => 1, 'icoco' => 1, 'chinatimes' => 1, 'videomo' => 1, 'voachinese' => 1,
            'fc2china' => 1, 'dailymotion' => 1, 'athenaeizou' => 1, 'nakuz' => 1, 'my-formosa' => 1, 'hongkongfp' => 1, 'igoogle' => 1, 'freealim' => 1,
            'x1949x' => 1, 'hkatvnews' => 1, 'palacemoon' => 1, 'cams' => 1, 'nytco' => 1, 'webworkerdaily' => 1, 'fullerconsideration' => 1, 'dadazim' => 1, 'retweeteffect' => 1, 'telecomspace' => 1,
            'thehousenews' => 1, 'yvesgeleyn' => 1, 'spencertipping' => 1, 'asiatgp' => 1, 'venbbs' => 1, 'zarias' => 1, 'lushstories' => 1, 'aisex' => 1,
            'curvefish' => 1, 'chubun' => 1, 'joeedelman' => 1, 'dynawebinc' => 1, 'epochtimestr' => 1, 'jbtalks' => 1, 'yobt' => 1, 'gaytube' => 1, 'iu45' => 1, 'tv-intros' => 1,
            'digisfera' => 1, 'singfortibet' => 1, 'mingpaotor' => 1, 'mingjingtimes' => 1, 'lamrim' => 1, 'ozyoyo' => 1, 'shenzhoufilm' => 1, 'cafepress' => 1, 'dtiserv2' => 1, 'happy-vpn' => 1, '141tube' => 1, 'xnxx' => 1,
            'yourlust' => 1, 'twitpic' => 1, 'cnabc' => 1, 'kurashsultan' => 1, 'newchen' => 1, 'lrfz' => 1, 'freeopenvpn' => 1, 'goodreads' => 1, 'googleplay' => 1, 'idaiwan' => 1,
            'foxsub' => 1, 'faproxy' => 1, 'torcn' => 1, 'mixx' => 1, 'twibase' => 1, 'iphone4hongkong' => 1, 'tweetdeck' => 1, 'pornhd' => 1,
            't35' => 1, 'thebobs' => 1, 'xlfmtalk' => 1, 'facebook' => 1, 'space-scape' => 1, 'dadi360' => 1, 'vpnvip' => 1, 'mychinamyhome' => 1, 'pornhost' => 1, 'nodesnoop' => 1,
            'newyorktimes' => 1, 'aofriend' => 1, 'fuq' => 1, 'talk853' => 1, 'duckload' => 1, 'videobam' => 1, 'stoweboyd' => 1, 'streema' => 1, 'zkaip' => 1, 'googlelabs' => 1,
            'vpnpronet' => 1, 'niusnews' => 1, 'mfxmedia' => 1, 'codeplex' => 1, 'yuvutu' => 1, 'officeoftibet' => 1, 'post852' => 1, 'experts-univers' => 1, 'gclooney' => 1, 'googlesyndication' => 1,
            'hkej' => 1, 'koolsolutions' => 1, 'mmmca' => 1, 'great-firewall' => 1, 'zynamics' => 1, 'boxpn' => 1, 'apkpure' => 1, 'anchorfree' => 1,
            'gospelherald' => 1, 'purevpn' => 1, 'hahlo' => 1, 'foxtang' => 1, 'hasaowall' => 1, 'startpage' => 1, 'anpopo' => 1, 'wanglixiong' => 1, 'tweetwally' => 1, 'pokerstrategy' => 1,
            'fring' => 1, 'xing' => 1, 'xinshijue' => 1, 'podictionary' => 1, 'stickeraction' => 1, 'appledaily' => 1, 'avfantasy' => 1, 'nysingtao' => 1, 'tapanwap' => 1, 'in-disguise' => 1,
            'tuxtraining' => 1, 'wenyunchao' => 1, 'mangafox' => 1, 'thetibetpost' => 1, 'xyy69' => 1, 'istarshine' => 1, 'helloandroid' => 1, 'wheretowatch' => 1, 'like' => 1, 'sexandsubmission' => 1,
            'noodlevpn' => 1, 'verybs' => 1, 'ozxw' => 1, 'alkasir' => 1, 'h-moe' => 1, 'typepad' => 1, 'galenwu' => 1, 'multiupload' => 1, 'unix100' => 1, 'robustnessiskey' => 1,
            'harunyahya' => 1, 'berlintwitterwall' => 1, 'liwangyang' => 1, 'girlbanker' => 1, '10musume' => 1, 'wet123' => 1, 'truveo' => 1, 'gather' => 1, 'javlibrary' => 1, 'ggpht' => 1, 'usacn' => 1, 'usejump' => 1,
            'funp' => 1, 'hentaivideoworld' => 1, 'jeanyim' => 1, 'maxgif' => 1, 'pixelqi' => 1, 'animeshippuuden' => 1, 'mgoon' => 1, 'cbsnews' => 1, 'chengmingmag' => 1, 'latelinenews' => 1,
            's1heng' => 1, 'freakshare' => 1, 'tvplayvideos' => 1, 'hk01' => 1, 'indiatimes' => 1, 'nytimg' => 1, 'instagram' => 1, 'mitbbs' => 1, 'trendsmap' => 1, 'kakao' => 1,
            'wiredbytes' => 1, 'eksisozluk' => 1, 'soundcloud' => 1, 'stackfile' => 1, 'tibetcollection' => 1, 'aiweiweiblog' => 1, '123rf' => 1, 'macrovpn' => 1, 'badoo' => 1, 'shahamat-english' => 1,
            'bbsland' => 1, 'ventureswell' => 1, 'savevid' => 1, 'pornoxo' => 1, 'squarespace' => 1, 'hkgolden' => 1, 'voatibetan' => 1, 'speckleapp' => 1, 'osaka69' => 1, 'bodog88' => 1,
            'twisternow' => 1, 881903 => 1, 'rapidmoviez' => 1, 'over-blog' => 1, 'dojin' => 1, 'ilovelongtoes' => 1, 'wuala' => 1, 'twit2d' => 1, 'netflix' => 1, 'punyu' => 1,
            'radiovncr' => 1, 'bl-doujinsouko' => 1, 'mediachinese' => 1, 'gutteruncensored' => 1, 'shapeservices' => 1, 'westernwolves' => 1, 'purepdf' => 1, 'larsgeorge' => 1,
            'abc' => 1, 'linkideo' => 1, 'phuquocservices' => 1, 'hmvdigital' => 1, 'getchu' => 1, 'geekerhome' => 1, 'jigsy' => 1, 'alternate-tools' => 1, 'marxist' => 1, 'kanzhongguo' => 1,
            'privatevpn' => 1, 'hegre-art' => 1, 'arstechnica' => 1, 'pk' => 1, 'palmislife' => 1, 'dlsite' => 1, 'wallproxy' => 1, 'shvoong' => 1, 'freenewscn' => 1, 'earthcam' => 1, 'googleusercontent' => 1, 'dish' => 1,
            'amazon' => 1, 'gvt1' => 1, 'teensinasia' => 1, 'himemix' => 1, 'eastturkestan' => 1, 'sydneytoday' => 1, 'whippedass' => 1, 'mycould' => 1, 'le-vpn' => 1, 'tmdfish' => 1,
            'nightlife141' => 1, 'openallweb' => 1, 'sis001' => 1, 'workatruna' => 1, 'guardster' => 1, 'gmiddle' => 1, 'centralnation' => 1, 'puffinbrowser' => 1, 'amiblockedornot' => 1, 'zhinengluyou' => 1,
            'hklft' => 1, 'thywords' => 1, 'hdzog' => 1, 'longmusic' => 1, 'wolfax' => 1, 'xvideos' => 1, 'deja' => 1, 'pwned' => 1, 'thumbzilla' => 1, 'icerocket' => 1, 'ntdtvla' => 1, 'asiansexdiary' => 1,
            'koornk' => 1, 'lobsangwangyal' => 1, 'chromercise' => 1, 'tweetbackup' => 1, 'updatestar' => 1, 'tibetfocus' => 1, 'penthouse' => 1, 'juhuaren' => 1, 'uploadstation' => 1, 'expofutures' => 1, 'wearn' => 1, 'zattoo' => 1, 'bettween' => 1, 'hautelookcdn' => 1,
            'kenengba' => 1, 'multiply' => 1, 'lipuman' => 1, 'porntube' => 1, 'wengewang' => 1, 'tunein' => 1, 'bunbunhk' => 1, 'uwants' => 1, 'tumutanzi' => 1, 'homedepot' => 1,
            'wqlhw' => 1, 'pbwiki' => 1, 'ruyiseek' => 1, '12vpn' => 1, 'eltondisney' => 1, 'extremetube' => 1, 'yeelou' => 1, 'corumcollege' => 1, 'hkheadline' => 1, 'sexhu' => 1,
            'martincartoons' => 1, 'tweepguide' => 1, 'collateralmurder' => 1, 'nanyang' => 1, 'bullogger' => 1, 'wikia' => 1, '4rbtv' => 1, '2shared' => 1, 'ranxiang' => 1, 'isohunt' => 1,
            'ibtimes' => 1, 'shafaqna' => 1, 'erepublik' => 1, 'unitedsocialpress' => 1, 'briefdream' => 1, 'ironicsoftware' => 1, 'avmoo' => 1, 'mayimayi' => 1, 'brazzers' => 1, 'beijing1989' => 1,
            'vpnbook' => 1, 'hkfreezone' => 1, 'vpntunnel' => 1, 'gigacircle' => 1, 'bowenpress' => 1, 'tvb' => 1, 'calebelston' => 1, 'versavpn' => 1, 'rd' => 1, 'centerforhumanreprod' => 1,
            'gvlib' => 1, 'liujianshu' => 1, 'daylife' => 1, 'chinesedemocracy' => 1, 'brainyquote' => 1, 'djorz' => 1, 'tenacy' => 1, 'mobile01' => 1, 'cynscribe' => 1, 'lockestek' => 1,
            'alanhou' => 1, '85st' => 1, 'broadpressinc' => 1, 'sunskyforum' => 1, 'rotten' => 1, 'meltoday' => 1, 'twtkr' => 1, 'atchinese' => 1, 'gazotube' => 1, 'nownews' => 1,
            '64wiki' => 1, 'bloglovin' => 1, 'popyard' => 1, 'mychinanews' => 1, 'oiktv' => 1, 'voy' => 1, 'thenewslens' => 1, 'sidelinesnews' => 1, 'friendfinder' => 1, 'ncol' => 1,
            'mthruf' => 1, 'memehk' => 1, 'orzdream' => 1, 'mog' => 1, 'naughtyamerica' => 1, 'gongminliliang' => 1, 'heywire' => 1, 'code1984' => 1, 'zacebook' => 1, 'sharebee' => 1,
            'dropboxusercontent' => 1, 'wenxuecity' => 1, 'veoh' => 1, 'dongyangjing' => 1, 'revocationcheck' => 1, 'lizhizhuangbi' => 1, 'brandonhutchinson' => 1, 'tibetanphotoproject' => 1, 'yourlisten' => 1, 'techlifeweb' => 1,
            'seapuff' => 1, 'tafaward' => 1, 'chromeexperiments' => 1, 'my-proxy' => 1, 'wn' => 1, 'ivacy' => 1, 'shodanhq' => 1, 'v2ray' => 1, 'huyandex' => 1, 'fflick' => 1,
            'sino-monthly' => 1, 'slutload' => 1, 'postadult' => 1, 'sakuralive' => 1, 'chenpokong' => 1, 'kcsoftwares' => 1, 'sourcewadio' => 1, 'plixi' => 1, 'gunsandammo' => 1, 'googlecommerce' => 1,
            'carabinasypistolas' => 1, 'facebookquotes4u' => 1, 'tuanzt' => 1, 'pornhub' => 1, 'vpn4all' => 1, 'utopianpal' => 1, 'ocaspro' => 1, 'ck101' => 1, 'to-porno' => 1, 'erktv' => 1,
            'juliepost' => 1, 'twapperkeeper' => 1, 'rushbee' => 1, 'faithfuleye' => 1, 'brockbbs' => 1, 'ifreewares' => 1, 'zoho' => 1, 'sendspace' => 1, 'allmovie' => 1, 'readmoo' => 1,
            'tibetsun' => 1, 'howtoforge' => 1, 'crackle' => 1, 'googlevideo' => 1, 'xml-training-guide' => 1, 'torvpn' => 1, 'effers' => 1, 'presentationzen' => 1, 'communitychoicecu' => 1,
            'freefuckvids' => 1, 'megaporn' => 1, 'crocotube' => 1, 'chinamule' => 1, 'trulyergonomic' => 1, 'atnext' => 1, 'twerkingbutt' => 1, 'twitgether' => 1, 'maiplus' => 1, 'wordpress' => 1,
            'awardwinningfjords' => 1, 'wetpussygames' => 1, 'nanzao' => 1, 'tubegals' => 1, '99btgc01' => 1, 's1s1s1' => 1, 'linglingfa' => 1, 'avyahoo' => 1, 'hkcoc' => 1, 'imgur' => 1,
            'ruanyifeng' => 1, 'cnyes' => 1, 'mychinanet' => 1, 'skybet' => 1, 'megavideo' => 1, 'rojo' => 1, 'jiepang' => 1, 'megaproxy' => 1, 'eulam' => 1, 'agoogleaday' => 1,
            'dizhuzhishang' => 1, 'tistory' => 1, 'tagwalk' => 1, 'wanz-factory' => 1, 'oyghan' => 1, 'overlapr' => 1, 'dizhidizhi' => 1, 'printfriendly' => 1, 'vocativ' => 1, 'ourdearamy' => 1,
            'sidelinessportseatery' => 1, 'ixxx' => 1, 'moviefap' => 1, 'shwchurch3' => 1, '63i' => 1, 'newgrounds' => 1, 'cyberctm' => 1, 'sex' => 1, 'duoweitimes' => 1, 'chingcheong' => 1,
            'buffered' => 1, 'xhamster' => 1, 'private' => 1, 'freemoren' => 1, 'blogblog' => 1, 'tiltbrush' => 1, 'van698' => 1, 'mlcool' => 1, 'omgili' => 1, 'alldrawnsex' => 1,
            'chromestatus' => 1, 'livevideo' => 1, 'weblagu' => 1, 'nlfreevpn' => 1, 'tibetsites' => 1, 'zyzc9' => 1, 'panoramio' => 1, 'dalailamajapanese' => 1, 'whylover' => 1, 'westca' => 1,
            'forums-free' => 1, '315lz' => 1, 'powerapple' => 1, 'txxx' => 1, 'hk32168' => 1, 'jizzthis' => 1, 'zalmos' => 1, 'getiton' => 1, 'belamionline' => 1, 'i2runner' => 1,
            'hidecloud' => 1, 'gcpnews' => 1, 'twifan' => 1, 'tweetphoto' => 1, 'law' => 1, 'chinatopsex' => 1, 'filthdump' => 1, 'gabocorp' => 1, 'googlecode' => 1, 'turbotwitter' => 1,
            'bigjapanesesex' => 1, 'free-ssh' => 1, 'tubewolf' => 1, 'xgmyd' => 1, 'chinesedailynews' => 1, 'viki' => 1, 'empfil' => 1, 'springboardplatform' => 1, 'mooo' => 1, 'provpnaccounts' => 1,
            'sinoquebec' => 1, 'cnitter' => 1, 'livestream' => 1, 'tibetanpaintings' => 1, 'rhcloud' => 1, 'sthoo' => 1, 'softwarebychuck' => 1, 'illusionfactory' => 1, 'efksoft' => 1, 'yakbutterblues' => 1,
            'staticflickr' => 1, 'calibre-ebook' => 1, 'metarthunter' => 1, 'nintendium' => 1, '21andy' => 1, 'stupidvideos' => 1, 'emulefans' => 1, 'porntubenews' => 1, 'mirrorbooks' => 1, 'razyboard' => 1,
            'hkbookcity' => 1, 'dongtaiwang' => 1, 'twimg' => 1, 'hardsextube' => 1, 'calgarychinese' => 1, 'twitlonger' => 1, 'coobay' => 1, 'googledomains' => 1, 'revleft' => 1, 'wingamestore' => 1,
            'drsunacademy' => 1, 'visiontimes' => 1, 'hqmovies' => 1, 'kindleren' => 1, 'zinio' => 1, 'atdmt' => 1, 'bbs-tw' => 1, 'snaptu' => 1,
            'ntdtv' => 1, 'mrdoob' => 1, 'sendoid' => 1, 'giganews' => 1, 'twitiq' => 1, 'huaglad' => 1, 'sorting-algorithms' => 1, 'go-pki' => 1, 'hkfaa' => 1, 'barracuda' => 1,
            'yibada' => 1, 'playboy' => 1, 'youjizz' => 1, 'imkev' => 1, 'inkui' => 1, 'realraptalk' => 1, 'listorious' => 1, 'bangyoulater' => 1, 'zaobao' => 1, 'youversion' => 1,
            'rlwlw' => 1, 'twitcause' => 1, 'flickr' => 1, 'godsimmediatecontact' => 1, 'ajsands' => 1, 'softether-download' => 1, 'waiwaier' => 1, 'waltermartin' => 1, 'hootsuite' => 1, 'michaelanti' => 1,
            'voachineseblog' => 1, 'skyvegas' => 1, 'vpnpop' => 1, 'kinghost' => 1, 'suroot' => 1, 'chinaeweekly' => 1, 'hola' => 1, 'mpettis' => 1, 'snowlionpub' => 1, 'tsunagarumon' => 1,
            'cherrysave' => 1, 'ienergy1' => 1, 'findmespot' => 1, 'dwnews' => 1, 'twitterfeed' => 1, 'goofind' => 1, 'hotspotshield' => 1, 'sopcast' => 1, 'fangongheike' => 1, 'nordstromrack' => 1,
            'proxifier' => 1, 'madthumbs' => 1, 'twittermail' => 1, 'uyghurpress' => 1, 'reflectivecode' => 1, 'hidemycomp' => 1, 'eromanga-kingdom' => 1, 'vpncoupons' => 1, 'nuuvem' => 1, 'tt1069' => 1,
            '6park' => 1, 'macgamestore' => 1, 'piring' => 1, 'internetpopculture' => 1, 'zootool' => 1, 'melon-peach' => 1, 'tweettunnel' => 1, 991 => 1, 'surfeasy' => 1, 'martau' => 1,
            'xn--4gq171p' => 1, 'edoors' => 1, 'etaiwannews' => 1, 'malaysiakini' => 1, 'lpsg' => 1, 'kusos' => 1, 'soifind' => 1, 'vpnfan' => 1, 'tube911' => 1, 'wujieliulan' => 1,
            'revver' => 1, 'twitturly' => 1, 'buzzhand' => 1, 'renminbao' => 1, 'yangjianli' => 1, 'getsocialscope' => 1, 'udnbkk' => 1, 'sejie' => 1, 'upornia' => 1, 'eucasino' => 1,
            'faydao' => 1, 'fb' => 1, 'sun1911' => 1, 'vincnd' => 1, 'comedycentral' => 1, 'linksalpha' => 1, 'gjczz' => 1, 'now' => 1, 'altrec' => 1, 'omnitalk' => 1, 'idlcoyote' => 1,
            'plunder' => 1, 'meteorshowersonline' => 1, 'ning' => 1, 'orchidbbs' => 1, 'dipity' => 1, 'netbig' => 1, 'bbcchinese' => 1, 'pin6' => 1, 'gmodules' => 1, 'feer' => 1,
            'madonna-av' => 1, 'logmein' => 1, 'bloomfortune' => 1, 'sfileydy' => 1, 'gaybubble' => 1, 'nanyangpost' => 1, 'python' => 1, 'cchere' => 1,
            'buugaa' => 1, 'maturejp' => 1, 'nordstrom' => 1, 'twitzap' => 1, 'xbookcn' => 1, 'sunporno' => 1, 'shenyun' => 1, 'geekmanuals' => 1,
            'barenakedislam' => 1, 'lamayeshe' => 1, 'retweetrank' => 1, 'bbtoystore' => 1, 'onmoon' => 1, 'jiaoyou8' => 1, 'spicevpn' => 1, 'asianspiss' => 1, 'frienddy' => 1,
            'localpresshk' => 1, 'scribd' => 1, 'withgoogle' => 1, 'mixpod' => 1, 'taragana' => 1, 'cn-proxy' => 1, 'geohot' => 1, 'voatibetanenglish' => 1, 'owind' => 1, 'phonegap' => 1,
            'r18' => 1, 'blueangellive' => 1, 'waselpro' => 1, 'hotpornshow' => 1, 'oopsforum' => 1, 'islamhouse' => 1, 'skype' => 1, 'youtube-nocookie' => 1, 'securetunnel' => 1, 'getcloak' => 1,
            'hsselite' => 1, 'briian' => 1, 'netcolony' => 1, 'kechara' => 1, 'break' => 1, 'suyangg' => 1, 'voanews' => 1, 'proxyroad' => 1, 's-cute' => 1, 'tttan' => 1,
            '51luoben' => 1, 'hnjhj' => 1, 'glock' => 1, 'nabble' => 1, 'read100' => 1, 'aomiwang' => 1, 'okayfreedom' => 1, 'twimbow' => 1, '1984bbs' => 1, 'iphonehacks' => 1,
            'woxinghuiguo' => 1, 'justtristan' => 1, 'longtoes' => 1, 'pmates' => 1, 'websnapr' => 1, 'waigaobu' => 1, 'adultfriendfinder' => 1, 'spike' => 1, 'vivatube' => 1, 'theatrum-belli' => 1,
            'snapchat' => 1, 'somee' => 1, 'acevpn' => 1, 'googleapis' => 1, 'sexhuang' => 1, '4tern' => 1, 'dzze' => 1, 'throughnightsfire' => 1, 'liuxiaotong' => 1, 'mymediarom' => 1,
            'towngain' => 1, 'justfreevpn' => 1, 'engadget' => 1, 'axureformac' => 1, '64tianwang' => 1, 'flitto' => 1, 'imageflea' => 1, 'dougscripts' => 1, 'kaotic' => 1, 'youporngay' => 1,
            'natado' => 1, 'sheikyermami' => 1, 'sextvx' => 1, 'go141' => 1, 'blinw' => 1, 'suprememastertv' => 1, 'ytimg' => 1, 'windowsphoneme' => 1, 'dafahao' => 1, 'urbansurvival' => 1,
            'sherabgyaltsen' => 1, 'epochtimes-bg' => 1, 'dharamsalanet' => 1, 'hotvpn' => 1, 'linkuswell' => 1, 'taiwankiss' => 1, 'freeweibo' => 1, 'gyalwarinpoche' => 1, 'bbsdigest' => 1, 'focusvpn' => 1,
            'sketchappsources' => 1, 'ifanr' => 1, 'kanshifang' => 1, 'freefq' => 1, 'twindexx' => 1, 'logmike' => 1, 'ultraxs' => 1, 'highrockmedia' => 1, 'yes-news' => 1, 'pengyulong' => 1,
            'prisoneralert' => 1, 'nordstromimage' => 1, 'mefeedia' => 1, 'xjtravelguide' => 1, 'chaturbate' => 1, 'strongvpn' => 1, 'websitepulse' => 1, 'mpinews' => 1, 'arctosia' => 1, 'ismalltits' => 1,
            'mycnnews' => 1, 'kodingen' => 1, 'hung-ya' => 1, 'duckduckgo' => 1, 'rangzen' => 1, 'boysmaster' => 1, 'indiemerch' => 1, 'threatchaos' => 1, 'cftfc' => 1, 'playno1' => 1,
            'farwestchina' => 1, 'inxian' => 1, 'xxbbx' => 1, 'chrome' => 1, 'hotgoo' => 1, 'china21' => 1, 'twblogger' => 1, 'penchinese' => 1, '92ccav' => 1, 'breakgfw' => 1,
            'singtao' => 1, 'backtotiananmen' => 1, 'cattt' => 1, 'meirixiaochao' => 1, 'x-art' => 1, 'keepvid' => 1, 'city9x' => 1, 'searchtruth' => 1, 'superpages' => 1, 'delicious' => 1,
            'thebcomplex' => 1, 'xfinity' => 1, 'noypf' => 1, 'livestation' => 1, 'wforum' => 1, 'tomayko' => 1, 'zuola' => 1, 'anonymitynetwork' => 1, 'eromangadouzin' => 1, 'hkjc' => 1,
            'want-daily' => 1, 'pacificpoker' => 1, 'glennhilton' => 1, 'konachan' => 1, 'carmotorshow' => 1, 'spotify' => 1, 'gunsamerica' => 1, 'chinalawtranslate' => 1, 'tuzaijidi' => 1, '36rain' => 1,
            'hornygamer' => 1, 'travelinlocal' => 1, 'aceros-de-hispania' => 1, 'shutterstock' => 1, 'yahoo' => 1, 'hongmeimei' => 1, 'minzhuzhanxian' => 1, 'huluim' => 1, 'eastern-ark' => 1, 'quran' => 1,
            'emaga' => 1, 'baywords' => 1, 'twitoaster' => 1, 'eslite' => 1, 'my903' => 1, 'spankwire' => 1, 'itshidden' => 1, 'chinahush' => 1, 'paljorpublications' => 1, 'huaxia-news' => 1,
            'cactusvpn' => 1, 'blogger' => 1, 'stumbleupon' => 1, 'have8' => 1, 'askstudent' => 1, 'b0ne' => 1, 'hellotxt' => 1, '30boxes' => 1, 'myspace' => 1, 'aenhancers' => 1,
            'safervpn' => 1, 'tianhuayuan' => 1, 'forum4hk' => 1, 'chinalawandpolicy' => 1, 'junauza' => 1, 'svwind' => 1, 'pinoy-n' => 1, 'flipboard' => 1, 'mingjinglishi' => 1, 'greenreadings' => 1,
            'privateinternetaccess' => 1, 'hgseav' => 1, 'advertfan' => 1, 'tubecup' => 1, 'javhip' => 1, 'yulghun' => 1, 'tu8964' => 1, 'fucd' => 1, 'bloomberg' => 1, 'fleshbot' => 1,
            'higfw' => 1, 'vinniev' => 1, 'jieshibaobao' => 1, 'googlemail' => 1, 'lamenhu' => 1, 'epochweekly' => 1, 'javbus' => 1, 'freelotto' => 1, 'tweetree' => 1, 'skykiwi' => 1,
            'truthcn' => 1, 'newsancai' => 1, 'game735' => 1, 'caochangqing' => 1, 'mrtweet' => 1, 'steel-storm' => 1, 'xxx' => 1, 'aamacau' => 1, 'ywpw' => 1, 'rfachina' => 1,
            'boxunclub' => 1, 'tzangms' => 1, 'eic-av' => 1, 'topsy' => 1, 'pose' => 1, 'edicypages' => 1, 'knowledgerush' => 1, 'ebookee' => 1, 'so-news' => 1, 'boobstagram' => 1,
            'elpais' => 1, 'pathtosharepoint' => 1, 'logiqx' => 1, 'bestvpnusa' => 1, 'elephantvpn' => 1, 'quranexplorer' => 1, 'github' => 1, 'laptoplockdown' => 1,
            'compileheart' => 1, 'gmail' => 1, 'expekt' => 1, 'playpcesor' => 1, 'isaacmao' => 1, 'hougaige' => 1, 'karayou' => 1, 'parkansky' => 1, 'aboutgfw' => 1, 'comefromchina' => 1,
            'vs' => 1, 'olumpo' => 1, 'state168' => 1, 'fzh999' => 1, 'topshareware' => 1, 'qstatus' => 1, 'commandarms' => 1, 'changp' => 1, 'unblockdmm' => 1, 'yimg' => 1, 'carfax' => 1, 'togetter' => 1,
            'interfaceaddiction' => 1, 'storagenewsletter' => 1, 'syncback' => 1, 'tweetboard' => 1, 'powerpointninja' => 1, 'orient-doll' => 1, 'twittercounter' => 1, 'git-scm' => 1,
            'csdparty' => 1, 'erodoujinworld' => 1, 'lingvodics' => 1, 'aliengu' => 1, 'taweet' => 1, '0to255' => 1, 'tkcs-collins' => 1, 'trustedbi' => 1, 'earthvpn' => 1,
            'persecutionblog' => 1, 'dtiblog' => 1, 'myaudiocast' => 1, 'mmdays' => 1, 'appspot' => 1, 'dollf' => 1, 'islamicity' => 1, '1eew' => 1, 'taiwannation' => 1,
            'allinfa' => 1, 'dcmilitary' => 1, 'btspread' => 1, 'kichiku-doujinko' => 1, 'wahas' => 1, 'goldenfrog' => 1, 'friendfeed-media' => 1, 'furinkan' => 1,
            'businessweek' => 1, 'camfrog' => 1, 'nordvpn' => 1, 'yourepeat' => 1, 'jgoodies' => 1, 'china-week' => 1, 'sex3' => 1, 'taiwanjustice' => 1, 'proxlet' => 1,
            'mingpao' => 1, 'unblock-us' => 1, 'getuploader' => 1, 'uymaarip' => 1, 'hket' => 1, 'ydy' => 1, 'vpncup' => 1, 'adorama' => 1, 'tibet' => 1, 'geometrictools' => 1,
            'gs-discuss' => 1, 'googleearth' => 1, 'blockcn' => 1, 'christianstudy' => 1, 'yeeyi' => 1, 'ebookbrowse' => 1, 'tweetedtimes' => 1, 'ixquick' => 1,
            'piposay' => 1, 'activpn' => 1, 'fangeming' => 1, 'vmixcore' => 1, 'twtrland' => 1, 'huhaitai' => 1, 'stackoverflow' => 1, 'yipub' => 1, 'franklc' => 1,
            'xiaohexie' => 1, 'freewebs' => 1, 'xxlmovies' => 1, 'dwheeler' => 1, 'famunion' => 1, '173ng' => 1, 'freeman2' => 1, 'fc2cn' => 1, 'coolncute' => 1, 'couchdbwiki' => 1,
            'sobees' => 1, 'busayari' => 1, 'googleideas' => 1, 'suissl' => 1, 'oyax' => 1, 'mobypicture' => 1, 'tibetonline' => 1, 'chosun' => 1, 'cos-moe' => 1,
            'wpoforum' => 1, 'openwebster' => 1, '91porn' => 1, 'wtfpeople' => 1, 'bmfinn' => 1,
        ),
        'jp' => array(
            'co' => array(
                'google' => 1, 'panacom' => 1, 'excite' => 1, 'sod' => 1, 'yahoo' => 1, 'kk-whys' => 1, 'softether' => 1, 'tma' => 1, 'exblog' => 1, 'geocities' => 1, 'dmm' => 1,
            ),
            'finalion' => 1, 'cam4' => 1, 'mvg' => 1, 'blogimg' => 1, 'giga-web' => 1, 'destroy-china' => 1, 'twipple' => 1, 'nexton-net' => 1, 'dlsite' => 1, 'wikiwiki' => 1,
            'or' => array(
                'yasukuni' => 1, 'raizoji' => 1,
            ),
            'kawaiikawaii' => 1, 'maxing' => 1, 'ameblo' => 1, 'orn' => 1, 'twitter' => 1, 'showtime' => 1, 'geocities' => 1,
            'ne' => array(
                'graphis' => 1, 'goo' => 1,
            ),
            'asdfg' => 1, 'duga' => 1, 'kir' => 1, 'eyevio' => 1, 'baidu' => 1, 'tibethouse' => 1, 'woopie' => 1, 'tono-oka' => 1, 'gamerp' => 1,
            'radiko' => 1, 'dl-laby' => 1, 'vpngate' => 1, 'exblog' => 1, 'switch1' => 1,
            'go' => array(
                'jma' => 1, 'npa' => 1,
            ),
            'epochtimes' => 1, 'immoral' => 1, 'ritouki' => 1, 'xcity' => 1, 'fdc89' => 1, 'meyou' => 1, 'tabtter' => 1,
        ),
        'kr' => array(
            'co' => array(
                'google' => 1, 'crossfire' => 1, 'ntdtv' => 1, 'epochtimes' => 1,
            ),
            'or' => array(
                'minghui' => 1, 'tongil' => 1,
            ),
            'soundofhope' => 1, 'thereallove' => 1,
        ),
        'hk' => array(
            'com' => array(
                'google' => 1, 'myforum' => 1, 'xinmiao' => 1, 'e-zone' => 1, 'sina' => 1, 'weather' => 1, 'sharpdaily' => 1, 'babynet' => 1,
                'metroradio' => 1, 'vjmedia' => 1, 'discuss' => 1, 'open' => 1, 'tvmost' => 1, 'am730' => 1, 'yahoo' => 1, 'metrohk' => 1, 'yesasia' => 1, 'greenfieldbookstore' => 1, 'hkdailynews' => 1,
            ),
            'org' => array(
                'emilylau' => 1, 'hklts' => 1, 'plm' => 1, 'hkhrm' => 1, 'efcc' => 1, 'adpl' => 1, 'workerdemo' => 1, 'gnci' => 1, 'catholic' => 1, 'gcc' => 1, 'pfd' => 1, 'cbtc' => 1,
                'chinayouth' => 1, 'hkja' => 1, 'sowers' => 1, 'lotuslight' => 1, 'rthk' => 1, 'tbi' => 1, 'alliance' => 1, 'dolf' => 1,
                'lsd' => 1, 'cfhks' => 1, 'salvation' => 1, 'islam' => 1, 'hkhrc' => 1, 'cap' => 1, 'szetowah' => 1, 'clb' => 1,
                'hkwcc' => 1, 'liberal' => 1, 'christiantimes' => 1,
            ),
            'left21' => 1, 'myradio' => 1, 'oclp' => 1, 'etvonline' => 1, 'bwsj' => 1, 'cusu' => 1, 'rthk' => 1, 'i1' => 1, 'popvote' => 1, 'sharpdaily' => 1,
            'guruonline' => 1, 'passiontimes' => 1, 'qooza' => 1, 'hku' => 1, 'citizenscommission' => 1, 'stage64' => 1, 2017 => 1, 'dbc' => 1, 'civicparty' => 1,
            'co' => 1, 'thefrontier' => 1,
            'edu' => array(
                'cuhk' => 1,
            ),
            'loved' => 1, 'uncyclopedia' => 1, 'ourtv' => 1, 'exchristian' => 1, 'longhair' => 1, 'roadshow' => 1, 'e123' => 1, 'pentoy' => 1, 'fail' => 1, 'sacom' => 1,
            'hotpot' => 1, 'mihk' => 1, 'chrlawyers' => 1, 'bfsh' => 1, 'tuo8' => 1, 'chinachannel' => 1,
        ),
        'sg' => array(
            'com' => array(
                'google' => 1, 'zaobao' => 1, 'singaporepools' => 1,
            ),
            'org' => array(
                'cams' => 1,
            ),
            'omy' => 1, 'cam4' => 1,
        ),
        'vn' => array(
            'com' => array(
                'google' => 1,
            ),
            'thegioitinhoc' => 1,
        ),
        'net' => array(
            'doubleclick' => 1, 'maiio' => 1, 'hihistory' => 1, 'sunvpn' => 1, 'uberproxy' => 1, 'chinman' => 1, 'jiruan' => 1, 'd100' => 1, 'prozz' => 1,
            'penchinese' => 1, 'favotter' => 1, 'liaowangxizang' => 1, 'imagezilla' => 1, 'lsforum' => 1, 'sorazone' => 1, 'slideshare' => 1, 'workersthebig' => 1,
            'so-ga' => 1, 'sethwklein' => 1, 'dupola' => 1, 'ieasynews' => 1, 'lkcn' => 1, 'zhangboli' => 1, 'gaopi' => 1, 'vpnforgame' => 1, 'middle-way' => 1, 'laqingdan' => 1,
            'swissvpn' => 1, 'freechina' => 1, 'ihakka' => 1, 'rosechina' => 1, 'freetibet' => 1, 'hkusu' => 1, 'alforattv' => 1, 'your-freedom' => 1, 'erabaru' => 1, 'taiwandaily' => 1,
            'akamaistream' => 1, 'eroticsaloon' => 1, 'centurys' => 1, 'amigobbs' => 1, 'dwnews' => 1, 'sytes' => 1, 'avmoo' => 1, 'slandr' => 1, 'chinese-hermit' => 1, 'photodharma' => 1,
            'furl' => 1, 'heqinglian' => 1, 'westkit' => 1, 'chinasucks' => 1, '1000giri' => 1, 'fuckcnnic' => 1, 'wizcrafts' => 1, 'gaozhisheng' => 1, 'dok-forum' => 1, 'ied2k' => 1,
            'tibetexpress' => 1, 'alwaysdata' => 1, 'chinadialogue' => 1, 'xinsheng' => 1, 'longtermly' => 1, 'webs-tv' => 1, 'chinasmile' => 1, 'bloodshed' => 1, 'chuizi' => 1, 'wujie' => 1,
            'cuiweiping' => 1, 'torguard' => 1, 'dtdns' => 1, 'stoptibetcrisis' => 1, 'xuchao' => 1, 'islamtoday' => 1, 'akamai' => 1, 'leafyvpn' => 1, 'mobatek' => 1, 'dnssec' => 1,
            'sexinsex' => 1, 'bravotube' => 1, 'goproxing' => 1, 'exploader' => 1, 'bayvoice' => 1, 'convio' => 1, 'fgmtv' => 1, 'bolehvpn' => 1, 'supertweet' => 1, 'hstern' => 1,
            'twittbot' => 1, 'wanderinghorse' => 1, 'facebook' => 1, 'htkou' => 1, 'oursweb' => 1, 'animecrazy' => 1, 'bangchen' => 1, 'seezone' => 1, 'pornmm' => 1, 'openvpn' => 1,
            'worldvpn' => 1, 'xpdo' => 1, 'rapbull' => 1, 'webwarper' => 1, 'eastturkistan' => 1, 'twistory' => 1, 'yecl' => 1, 'geek-art' => 1, 'mattwilcox' => 1, 'verizon' => 1,
            'tibet-info' => 1, 'mullvad' => 1, 'breakwall' => 1, 'hackthatphone' => 1, 'radiohilight' => 1, 'vpninja' => 1, 'secureserver' => 1, 'xianqiao' => 1, 'tibetaction' => 1, 'box' => 1, 'dmcdn' => 1,
            'tomonews' => 1, 'talkonly' => 1, 'clearharmony' => 1, 'soulcaliburhentai' => 1, 'tibetanreview' => 1, 'falundafa-pa' => 1, 'fbcdn' => 1, 'edgecastcdn' => 1, 'globalrescue' => 1, 'wow-life' => 1,
            'ai-wen' => 1, 'bipic' => 1, '12vpn' => 1, 'danke4china' => 1, 'vraiesagesse' => 1, 'kendincos' => 1, 'qusi8' => 1, 'rocket-inc' => 1, 'hsjp' => 1, '8z1' => 1,
            'twstar' => 1, 'ignitedetroit' => 1, 'tuidang' => 1, 'ecministry' => 1, 'chinainperspective' => 1, 'itweet' => 1, 'muzi' => 1, 'chenpokong' => 1, 'wangafu' => 1, 'sourceforge' => 1,
            'ctfriend' => 1, 'zhanbin' => 1, 'himemix' => 1, 'bdsmvideos' => 1, 'rapidgator' => 1, 'onmoon' => 1, 'hutianyi' => 1, 'zhongguotese' => 1, 'jkforum' => 1, 'xuite' => 1,
            'erights' => 1, 'hua-yue' => 1, '9bis' => 1, 'nubiles' => 1, 'packetix' => 1, 'new-3lunch' => 1, 'vpngate' => 1, 'web2project' => 1, 'ettoday' => 1, 'xuzhiyong' => 1,
            'nekoslovakia' => 1, 'watchmygf' => 1, 'panluan' => 1, 'googlezip' => 1, 'rxhj' => 1, 'uwants' => 1, 'kyohk' => 1, '85cc' => 1, 'fengzhenghu' => 1, 'proxytunnel' => 1, 'hstt' => 1,
            'homeip' => array(
                'derekhsu' => 1,
            ),
            'sockslist' => 1, 'witopia' => 1, 'softlayer' => 1, 'szbbs' => 1, 'kompozer' => 1, 'greatfirewallofchina' => 1, 'hutong9' => 1, 'falunpilipinas' => 1, 'hideman' => 1, 'greenvpn' => 1,
            'contactmagazine' => 1, 'greasespot' => 1, 'bcchinese' => 1, 'wukangrui' => 1, 'yx51' => 1, 'yunchao' => 1, 'ironpython' => 1, 'osmdroid' => 1,
            'frommel' => 1, 'yegle' => 1, 'blogtd' => 1, 'pixnet' => 1, 'fakku' => 1, 'yhcw' => 1, 'hdtvb' => 1, 'evschool' => 1, 'washeng' => 1, 'zgzcjj' => 1,
            'drgan' => 1, 'openid' => 1, 'crossthewall' => 1, 'fuyin' => 1, 'pandapow' => 1, 'old-cat' => 1, 'woesermiddle-way' => 1, 'jyxf' => 1,
            'flickrhivemind' => 1, 'hexxeh' => 1, 'shiatv' => 1, 'liangyou' => 1, 'askynz' => 1, 'gun-world' => 1, 'matome-plus' => 1, 'tibetancommunityuk' => 1, 'lianyue' => 1, 'islamawareness' => 1,
            'hinet' => 1, 'helixstudios' => 1, 'hecaitou' => 1, 'zomobo' => 1, 'sesawe' => 1, 'fotop' => 1, 'ulike' => 1, 'appsocks' => 1, 'switchvpn' => 1, 'qx' => 1,
            'willw' => 1, 'gizlen' => 1, 'chinadigitaltimes' => 1,
            'jp' => array(
                'china-mmm' => 1,
            ),
            'logbot' => 1, 'tibettimes' => 1, 'fc2blog' => 1, 'junefourth-20' => 1, 'fromchinatousa' => 1, 'huping' => 1, 'tibetinfonet' => 1, 'quitccp' => 1, 'streamingthe' => 1, 'oauth' => 1,
            'zshare' => 1, 'teeniefuck' => 1, 'aiph' => 1, 'blingblingsquad' => 1, 'fzh999' => 1, 'creaders' => 1, 'minzhuhua' => 1, 'keontech' => 1,
            'slyip' => 1, 'sysadmin1138' => 1, 'organharvestinvestigation' => 1, '3tui' => 1, 'uploaded' => 1, 'recaptcha' => 1, 'uighurbiz' => 1, 'nhentai' => 1,
            'sneakme' => 1, 'goldstep' => 1, 'letscorp' => 1, '1e100' => 1, 'marxist' => 1, 'globaljihad' => 1, 'ai-kan' => 1, 'journalchretien' => 1, 'chinaaid' => 1, 'changsa' => 1,
            'site90' => 1, 'dongtaiwang' => 1, 'delcamp' => 1, 'gdbt' => 1, 'perfectgirls' => 1, 'taiwantp' => 1, 'fofg-europe' => 1, 'overplay' => 1, 'd0z' => 1, 'thehun' => 1,
            'brucewang' => 1, 'compython' => 1, 'webbang' => 1, 'pentalogic' => 1, 'fanqiangyakexi' => 1, 'fhreports' => 1, 'classicalguitarblog' => 1, 'antiwave' => 1, 'daolan' => 1, 'taiwanus' => 1,
            'china-mmm' => 1, 'vpngratis' => 1, 'rolia' => 1, 'clearwisdom' => 1, 'tibet' => 1, 'hkbc' => 1, 'buzzhand' => 1, 'hkday' => 1, 'pao-pao' => 1, 'al-qimmah' => 1,
            'twitbrowser' => 1, 'turbobit' => 1, 'ismprofessional' => 1, 'artsy' => 1, 'wangruoshui' => 1, 'bewww' => 1, 'wsj' => 1, 'cablegatesearch' => 1, 'toonel' => 1, 'ipjetable' => 1,
            'tonyyan' => 1, 'ddns' => 1, 'sapikachu' => 1, 'yuanming' => 1, 'taoism' => 1, 'prayforchina' => 1, 'gaoming' => 1, 'iconfactory' => 1, 'tiananmenuniv' => 1, 'wezone' => 1,
            'ytht' => 1, 'ivpn' => 1, 'proxypy' => 1, 'izles' => 1, 'cjb' => 1, 'andfaraway' => 1, 'gaycn' => 1, 'chinesetalks' => 1, 'igcd' => 1, 'gmiddle' => 1,
            'adultkeep' => 1, 'picidae' => 1, 'taup' => 1, 'xinyubbs' => 1, 'rangzen' => 1, 'opera-mini' => 1, 'swift-tools' => 1, 'igfw' => 1, 'catch22' => 1, 'appdownloader' => 1,
            'soul-plus' => 1, 'finler' => 1, 'zoozle' => 1, 'stuffimreading' => 1, 'faluninfo' => 1, 'raremovie' => 1, 'freeyoutubeproxy' => 1, 'daiphapinfo' => 1, 'darktoy' => 1, 'inmediahk' => 1, 'duping' => 1, 'falunworld' => 1,
            'surrenderat20' => 1, 'observechina' => 1, 'pureconcepts' => 1, 'sowiki' => 1, 'javhub' => 1, 'calgarychinese' => 1, 'opendemocracy' => 1, 'naitik' => 1,
            'e-traderland' => 1, 'iblogserv-f' => 1, 'perfectvpn' => 1, 'jpopforum' => 1, 'tsctv' => 1, 'falun-ny' => 1, 'limiao' => 1,
        ),
        'org' => array(
            'bitcointalk' => 1, 'transparency' => 1, 'wikinews' => 1, 'joachims' => 1, 'alexlur' => 1, 'norbulingka' => 1, 'airvpn' => 1, 'zhongmeng' => 1,
            'jingpin' => 1, 's-dragon' => 1, 'kagyuoffice' => 1, 'fochk' => 1, 'rfamobile' => 1, 'tw-npo' => 1, 'episcopalchurch' => 1, 'powerphoto' => 1,
            'godfootsteps' => 1, 'bigsound' => 1, 'sipml5' => 1, 'jwmusic' => 1, 'dalailamacenter' => 1, 'freedomcollection' => 1, 'dyndns' => 1, 'rfa' => 1, 'xiuren' => 1, 'ccim' => 1,
            'circlethebayfortibet' => 1, 'fpmt' => 1, 'edupro' => 1, 'fgmtv' => 1, 'futuremessage' => 1, 'iredmail' => 1, 'antd' => 1, 'openleaks' => 1, 'nwtca' => 1, 'freedomsherald' => 1,
            'tew' => 1, 'wikibooks' => 1, 'shangfang' => 1, 'hkzone' => 1, 'filmingfortibet' => 1, 'xiaoma' => 1, 'chinaaid' => 1, 'wangruowang' => 1,
            'internetfreedom' => 1, 'wikipedia' => 1, 'sprite' => 1, 'greenvpn' => 1, 'orzistic' => 1, 'golang' => 1, 'ap' => 1, 'dalailamaquotes' => 1,
            'feitianacademy' => 1, 'fangong' => 1, 'codeskulptor' => 1, 'ifjc' => 1, 'lupm' => 1, 'vllcs' => 1, 'flnet' => 1, 'civilhrfront' => 1, 'clementine-player' => 1,
            'otnd' => 1, 'wokar' => 1, 'rangzen' => 1, 'freedomhouse' => 1, 'shixiao' => 1, 'karmapa' => 1, 'china18' => 1, 'rocmp' => 1, 'gardennetworks' => 1, 'cdpwu' => 1,
            'xuchao' => 1, 'freeoz' => 1, 'tanc' => 1, 'uc-japan' => 1, 'rukor' => 1, 'iphonetaiwan' => 1, 'zhenghui' => 1, 'iuhrdf' => 1, 'markmail' => 1, '908taiwan' => 1,
            'lerosua' => 1, 'tibetanpoliticalreview' => 1, 'redchinacn' => 1, 'fourthinternational' => 1, 'dvorak' => 1, 'suoluo' => 1, 'ntdtv' => 1, 'lsm' => 1, 'duihuahrjournal' => 1, 'chinasoul' => 1,
            'eastturkistancc' => 1, 'labiennale' => 1, 'cpj' => 1, 'soundofhope' => 1, 'ghost' => 1, 'tbjyt' => 1, 'falundafaindia' => 1, 'rigpa' => 1, 'clarionproject' => 1,
            'democrats' => 1, 'ghut' => 1, 'cuihua' => 1, 'ibros' => 1, 'tibetanliberation' => 1, 'icl-fi' => 1, 'laogai' => 1, 'mahabodhi' => 1, 'morningsun' => 1, 'blogtd' => 1, 'helpzhuling' => 1, 'allgirlsallowed' => 1,
            'tibetjustice' => 1, 'biblesforamerica' => 1, 'karmapa-teachings' => 1, 'pureinsight' => 1, 'tbsn' => 1, 'sambhota' => 1, 'journalofdemocracy' => 1, 'tibetanaidproject' => 1, 'wikimapia' => 1, 'bjzc' => 1,
            'cardinalkungfoundation' => 1, 'gdzf' => 1, 'cdpweb' => 1, 'ccdtr' => 1, 'drmingxia' => 1, 'dalianmeng' => 1, 'futurechinaforum' => 1, 'hikinggfw' => 1, 'chinarightsia' => 1, 'dastrassi' => 1,
            'furbo' => 1, 'christianfreedom' => 1, 'cipfg' => 1, 'westernshugdensociety' => 1, 'rfaweb' => 1, 'hkgreenradio' => 1, 'internationalrivers' => 1, 'whyx' => 1, 'yuanzhengtang' => 1,
            'hkptu' => 1, 'hrichina' => 1, 'tibetwrites' => 1, 'taiwandc' => 1, 'monitorchina' => 1, 'bullog' => 1, '24smile' => 1, 'englishforeveryone' => 1, 'chithu' => 1, 'wefightcensorship' => 1,
            'btdigg' => 1, 'purplelotus' => 1, 'chinachange' => 1, 'simplecd' => 1, '4chan' => 1, 'peopo' => 1, 'hxwk' => 1, 'putty' => 1, 'uocn' => 1, 'himalayan-foundation' => 1,
            'sogoo' => 1, 'cdbook' => 1, 'chinacomments' => 1, 'hkchurch' => 1, 'chinafreepress' => 1, 'globaltm' => 1, 'minghui-b' => 1, 'hellouk' => 1, 'mercyprophet' => 1, 'frontlinedefenders' => 1,
            'xizang-zhiye' => 1, 'dalailamatrust' => 1, 'wtbn' => 1, 'nobelprize' => 1, 'tuidang' => 1, 'khatrimaza' => 1, 'tuo8' => 1, 'tafm' => 1, 'lsmchinese' => 1, 'whatbrowser' => 1, 'accim' => 1, 'grandtrial' => 1,
            'holyspiritspeaks' => 1, 'cclifefl' => 1, 'hkfront' => 1, 'dnscrypt' => 1, 'eastturkistan-gov' => 1, 'huaxiabao' => 1, 'twitter4j' => 1, 'tbswd' => 1, 'dmhy' => 1, 'thepiratebay' => 1, 'bignews' => 1, 'shitaotv' => 1,
            'sharecool' => 1, 'wireshark' => 1, 'fuckgfw' => 1, 'pearlher' => 1, 'neverforget8964' => 1, 'aojiao' => 1, 'ogaoga' => 1, 'huanghuagang' => 1, 'statueofdemocracy' => 1, 'realcourage' => 1,
            'bic2011' => 1, 'newscn' => 1, 'ctao' => 1, 'latibet' => 1, 'zhuichaguoji' => 1, 'tibet-foundation' => 1, 'sftindia' => 1, 'vcfbuilder' => 1, 'internetdefenseleague' => 1, 'ohchr' => 1, 'weijingsheng' => 1,
            'lhakar' => 1, 'atgfw' => 1, 'tw01' => 1, 'ampproject' => 1, 'graylog2' => 1, 'c-spanvideo' => 1, 'minghui-school' => 1, 'moztw' => 1, 'angularjs' => 1, 'friendsoftibet' => 1, 'fqok' => 1, 'freebrowser' => 1,
            'vital247' => 1, 'transgressionism' => 1, 'bannednews' => 1, 'tchrd' => 1, 'chinamz' => 1, 'shadowsocks' => 1, 'uyghuramerican' => 1, 'tbthouston' => 1,
            'tbs-rainbow' => 1, 'falun-co' => 1, 'ncn' => 1, 'chinaway' => 1, 'e-hentai' => 1, 'uyghurcongress' => 1, 'turansam' => 1, 'ihao' => 1,
            'freebearblog' => 1, 'tbicn' => 1, 'religioustolerance' => 1, 'great-roc' => 1, 'dalailamafoundation' => 1, 'lvhai' => 1, 'politicalchina' => 1, 'asiaharvest' => 1,
            'bestforchina' => 1, 'honeynet' => 1, 'ernestmandel' => 1, 'freeforums' => 1, 'tibetoralhistory' => 1, '64museum' => 1, 'uyghurpen' => 1, 'sakya' => 1,
            'tbsec' => 1, 'falundafa-florida' => 1, 'tiandixing' => 1, 'yyii' => 1, 'proxy' => 1, 'futureme' => 1, 'greatzhonghua' => 1, 'amnesty' => 1, 'cnd' => 1, 'kba-tx' => 1,
            'smhric' => 1, 'fillthesquare' => 1, 'cdp2006' => 1, 'eu' => 1, 'wikivoyage' => 1, 'uhdwallpapers' => 1, 'dalailama80' => 1, 'android-x86' => 1,
            'globalvoicesonline' => 1, 'hrcchina' => 1, 'falundafa-dc' => 1, 'freetibet' => 1, 'hrw' => 1, 'truebuddha-md' => 1, 'vot' => 1, 'vidinfo' => 1, 'md-t' => 1, 'qxbbs' => 1,
            'uproxy' => 1, 'quitccp' => 1, 'citizenlab' => 1, 'faststone' => 1, 'art4tibet1998' => 1, 'wrchina' => 1, 'tibetanyouth' => 1, 'data-vocabulary' => 1, 'politicalconsultation' => 1, 'chinahorizon' => 1, 'mindrolling' => 1, 'uyghur-j' => 1,
            'uhrp' => 1, 'friends-of-tibet' => 1, 'hopto' => 1, 'tbcollege' => 1, 'dfn' => 1, 'mhradio' => 1, '1998cdp' => 1, 'falundafa-nc' => 1, 'c100tibet' => 1, 'casadeltibetbcn' => 1,
            'marxists' => 1, 'w3' => 1, 'tibetanwomen' => 1, 'cuhkacs' => 1, 'debian' => 1, 'worldcat' => 1, '100ke' => 1, 'tcewf' => 1, 'pbs' => 1, 'wiktionary' => 1,
            'thechinabeat' => 1, 'thechinastory' => 1, 'tibetanculture' => 1, 'nalandawest' => 1, 'cdp1989' => 1, 'huayuworld' => 1, 'chinaelections' => 1, 'wqyd' => 1,
            'taipeisociety' => 1, 'torproject' => 1, 'italiatibet' => 1, 'tnp' => 1, 'vermonttibet' => 1, 'ministrybooks' => 1, 'djangosnippets' => 1, 'answering-islam' => 1,
            'taa-usa' => 1, 'fpmt-osel' => 1, 'free-hada-now' => 1, 'freemuse' => 1, 'asacp' => 1, 'cgdepot' => 1, 'tibetsupportgroup' => 1, 'tibetanyouthcongress' => 1, 'pbxes' => 1,
            'thomasbernhard' => 1, 'avidemux' => 1, 'shenshou' => 1, 'areca-backup' => 1, 'gmll' => 1, 'molihua' => 1, 'hungerstrikeforaids' => 1, 'rtalabel' => 1, 'akademiye' => 1,
            'btku' => 1, 'mh4u' => 1, 'naacoalition' => 1, 'miniforum' => 1, 'freetibetanheroes' => 1, 'mswe1' => 1, 'upholdjustice' => 1, 'popyard' => 1,
            'alasbarricadas' => 1, 'vpnaccount' => 1, 'isgreat' => 1, 'rerouted' => 1, 'lotsawahouse' => 1, 'freeilhamtohti' => 1, 'memrijttm' => 1, 'lsmkorean' => 1,
            'hkdf' => 1, 'tt-rss' => 1, 'izlesem' => 1, 'wjbk' => 1, 'ned' => 1, 'ibiblio' => 1, 'rsgamen' => 1, 'tparents' => 1, 'tibetoffice' => 1, 'woyaolian' => 1,
            'sitemaps' => 1, 'linuxtoy' => 1, 'greatroc' => 1, 'twbbs' => 1, 'hqcdp' => 1, 'hkjp' => 1, 'olympicwatch' => 1, 'furhhdl' => 1, 'gaforum' => 1,
            'newstapa' => 1, 'falunart' => 1, 'unknownspace' => 1, 'khabdha' => 1, 'nokogiri' => 1, '1984bbs' => 1, 'bannedbook' => 1, 'tibetanlanguage' => 1, 'vimperator' => 1, 'fangmincn' => 1,
            'multiproxy' => 1, 'feitian-california' => 1, 'twftp' => 1, 'monlamit' => 1, 'june4commemoration' => 1, '1bao' => 1, 'martsangkagyuofficial' => 1,
            'zengjinyan' => 1, 'tensorflow' => 1, 'socrec' => 1, 'chinesepen' => 1, 'chromium' => 1, 'chinalaborwatch' => 1, 'lesscss' => 1, 'webmproject' => 1,
            'tibet' => 1, 'wikisource' => 1, 'amnyemachen' => 1, 'chinagreenparty' => 1, 'fireofliberty' => 1, 'kingdomsalvation' => 1, 'rtycminnesota' => 1, 'wan-press' => 1, 'duihua' => 1, 'internet' => 1,
            'yinlei' => 1, 'grangorz' => 1, 'imb' => 1, 'rsf' => 1, 'wangjinbo' => 1, 'dowei' => 1, 'fpmtmexico' => 1, 'cdjp' => 1, 'uyghurcanadiansociety' => 1, 'hxwq' => 1,
            'chinagfw' => 1, 'sylfoundation' => 1, 'tibetnetwork' => 1, 'taiwanembassy' => 1, 'sftuk' => 1, 'twiggit' => 1, 'waikeung' => 1, 'nvquan' => 1, 'falundafa' => 1, 'sonidodelaesperanza' => 1,
            'tibet3rdpole' => 1, 'thetibetmuseum' => 1, 'digitalnomadsproject' => 1, 'pttvan' => 1, 'mihua' => 1, 'cdp1998' => 1, 'wallornot' => 1, 'jingsim' => 1, 'studentsforafreetibet' => 1, 'cdef' => 1,
            'insecam' => 1, 'innermongolia' => 1, 'qienkuen' => 1, 'qvodzy' => 1, 'hidden-advent' => 1, 'wango' => 1, 'wengewang' => 1, 'globalmuseumoncommunism' => 1,
            'falunhr' => 1, 'radicalparty' => 1, 'vijayatemple' => 1, 'humanrightsbriefing' => 1, '89-64' => 1, 'tccwonline' => 1, 'ifcss' => 1, 'wemigrate' => 1, 'tbsseattle' => 1, 'vatn' => 1,
            'tibetfund' => 1, 'duckdns' => 1, 'justicefortenzin' => 1, 'falundafamuseum' => 1, 'hkbf' => 1, 'tbssqh' => 1, 'ancsconf' => 1, 'rferl' => 1, 'rsf-chinese' => 1,
            'lookingglasstheatre' => 1, 'cnpolitics' => 1, 'memri' => 1, 'moegirl' => 1, 'pornbase' => 1, 'danwei' => 1, 'sopcast' => 1, 'etizer' => 1, 'in99' => 1, 'getlantern' => 1,
            'chhongbi' => 1, 'greatfire' => 1, 'gerefoundation' => 1, 'change' => 1, 'wikileaks' => 1, 'exmormon' => 1, 'freenet-china' => 1, 'wisdompubs' => 1, 'upwill' => 1, 'tiananmenmother' => 1,
            'chinageeks' => 1, 'tibethouse' => 1, 'october-review' => 1, 'polymer-project' => 1, 'pcij' => 1, 'recoveryversion' => 1, 'hizbuttahrir' => 1, 'torrenty' => 1, 'tibetmuseum' => 1, 'youpai' => 1,
            'hrweb' => 1, 'hrea' => 1, 'mondex' => 1, 'h1n1china' => 1, 'iconpaper' => 1, 'fofldfradio' => 1, 'hizb-ut-tahrir' => 1, 'twilog' => 1, 'tianzhu' => 1, 'recordhistory' => 1,
            'sesawe' => 1, '1949er' => 1, 'familyfed' => 1, 'thetibetconnection' => 1, 'xpud' => 1, '5isotoi5' => 1, 'wexiaobo' => 1, 'h-china' => 1, 'braumeister' => 1, 'greatfirewallofchina' => 1,
            'citizensradio' => 1, 'chinaaffairs' => 1, 'nighost' => 1, 'trialofccp' => 1, 'jinbushe' => 1, 'dalailamainaustralia' => 1, 'sohfrance' => 1, 'china21' => 1, 'tibetanarts' => 1, 'avaaz' => 1,
            'fawanghuihui' => 1, 'x-wall' => 1, 'tibetanfeministcollective' => 1, 'guancha' => 1, 'chinayuanmin' => 1, 'archive' => 1, 'nalandabodhi' => 1, 'daliulian' => 1, 'xinhuanet' => 1,
            'dreammask' => 1, 'churchinhongkong' => 1, 'fscked' => 1, 'crchina' => 1, 'ucam' => 1, 'uncyclomedia' => 1, 'savetibet' => 1, 'gaozhisheng' => 1,
            'chinese-leaders' => 1, 'la-forum' => 1, 'weiquanwang' => 1, 'cclife' => 1, 'collateralmurder' => 1, 'waltermartin' => 1, 'tibetanbuddhistinstitute' => 1, 'luke54' => 1,
            'yogichen' => 1, 'pekingduck' => 1, 'kangye' => 1, 'amnestyusa' => 1, 'chinainterimgov' => 1, 'xysblogs' => 1, 'releaseinternational' => 1, 'dphk' => 1, 'lrip' => 1, 'uygur' => 1,
            'minzhuzhongguo' => 1, 'icij' => 1, 'tacem' => 1, 'w' => 1, 'shicheng' => 1, 'no-ip' => 1, 'tibetaid' => 1, 'tiantibooks' => 1, 'twyac' => 1, 'shizhao' => 1, 'budaedu' => 1, 'izihost' => 1, 'cdpeu' => 1, 'xys' => 1,
            'chinainperspective' => 1, 'bjnewlife' => 1,
            'aircrack-ng' => 1, 'busu' => 1, 'radiovaticana' => 1, 'unpo' => 1, 'gmhz' => 1, 'roc-taiwan' => 1, 'juyuange' => 1, 'nationsonline' => 1, 'peacefire' => 1, 'jamaat' => 1,
            'pastie' => 1, 'easternlightning' => 1, 'godsdirectcontact' => 1, 'zhengwunet' => 1, 'ucdc1998' => 1, 'cochina' => 1, 'tibetheritagefund' => 1, 'hanminzu' => 1, 'tmpp' => 1, 'thewgo' => 1, 'fofg' => 1,
            'sciencemag' => 1, 'tweepml' => 1, 'gu-chu-sum' => 1, 'victimsofcommunism' => 1, 'smyxy' => 1, 'youthnetradio' => 1, 'institut-tibetain' => 1, 'civisec' => 1,
            'tbsmalaysia' => 1, 'omnitalk' => 1, 'dalailamafellows' => 1, 'cmoinc' => 1, 'bfnn' => 1, 'tibetan-alliance' => 1, 'free-gate' => 1, 'zhongguorenquan' => 1, 'etowns' => 1, 'doctorvoice' => 1,
            'shenyunperformingarts' => 1, 'cdpusa' => 1, 'standupfortibet' => 1, 'getfoxyproxy' => 1, 'communistcrimes' => 1, 'scihub' => 1, 'vcf-online' => 1, 'de-sci' => 1,
            'cmule' => 1, 'hola' => 1, 'telegram' => 1, 'guishan' => 1, 'christusrex' => 1, 'tibetcorps' => 1, 'lantosfoundation' => 1, 'mykomica' => 1, 'wezhiyong' => 1, 'greenpeace' => 1,
            'chuang-yen' => 1, 'sysresccd' => 1, 'renyurenquan' => 1, 'chinese-memorial' => 1, 'canyu' => 1, 'javakiba' => 1, 'crd-net' => 1, 'shwchurch' => 1, 'diaoyuislands' => 1, 'initiativesforchina' => 1,
            'freenetproject' => 1, 'certificate-transparency' => 1, 'thetibetcenter' => 1, 'minghui-a' => 1, 'dtwang' => 1, 'webjb' => 1, 'minghui' => 1, 'softether' => 1,
            'drepung' => 1, 'icu-project' => 1, 'njactb' => 1,
        ),
        'eu' => array(
            'tibetoffice' => 1, 'tibetpolicy' => 1, 'glass8' => 1, 'hugoroy' => 1, 'cn6' => 1, 'mp3ye' => 1, 'dajiyuan' => 1, 'nyaa' => 1, 'usaip' => 1, 'tibet-envoy' => 1,
            'wikileaks' => 1, 'europa' => 1, 'cenews' => 1, 'torrentz' => 1, 'qtrac' => 1, 'dabr' => 1, 'kanzhongguo' => 1,
        ),
        'tw' => array(
            'idv' => 1,
            'com' => array(
                'yahoo' => 1, 'trtc' => 1, 'recoveryversion' => 1, 'cts' => 1, 'msn' => 1, 'cna' => 1, 'setty' => 1, 'gohappy' => 1,
                'gvm' => 1, 'raidtalk' => 1, 'plays' => 1, 'pcstore' => 1, 'myav' => 1, 'qgirl' => 1, 'iset' => 1, 'ticket' => 1, 'gamebase' => 1, 'ithome' => 1,
                'oikos' => 1, 'ttv' => 1, 'taiwannation' => 1, '8news' => 1, 'sina' => 1, 'readingtimes' => 1, 'newtaiwan' => 1, 'ksnews' => 1, 'ltn' => 1, 'iptv' => 1,
                'cdnews' => 1, 'thywords' => 1, 'i-part' => 1, 'pubu' => 1, 'bcc' => 1, 'news100' => 1, 'backpackers' => 1, 'hotfrog' => 1,
                'macts' => 1, 'ddc' => 1, 'nch' => 1, 'merit-times' => 1, 'goodtv' => 1, 'url' => 1, 'kimy' => 1, 'ctitv' => 1,
                'nexttv' => 1, 'pchome' => 1, 'krtco' => 1, 'gamer' => 1, 'cw' => 1, 'youthwant' => 1, 'nextmag' => 1, 'khmusic' => 1,
                'raidcall' => 1, 'greenpeace' => 1, 'kingstone' => 1, 'southnews' => 1, 'libertytimes' => 1, 'e-classical' => 1, 'shop2000' => 1, 'tvbs' => 1,
                'igotmail' => 1, 'python' => 1, 'taconet' => 1, 'books' => 1, 'sanmin' => 1, 'taiwannews' => 1, 'yes123' => 1, 'vft' => 1,
                'uforadio' => 1, 'treemall' => 1, 'gamez' => 1, 'zdnet' => 1, 'slime' => 1, 'pcdvd' => 1, 'book' => 1, '1-apple' => 1,
            ),
            'inote' => 1,
            'org' => array(
                'pts' => 1, 'lighten' => 1, 'dpp' => 1, 'pct' => 1, 'kagyuoffice' => 1, 'twnorth' => 1, 'nccwatch' => 1, 'hakkatv' => 1, 'unification' => 1, 'coolloud' => 1, 'cathvoice' => 1, 'gati' => 1,
                'ipcf' => 1, 'fuyu' => 1, 'ait' => 1, 'organcare' => 1, 'recovery' => 1, 'taedp' => 1, 'tibet' => 1, 'catholic' => 1, 'tpi' => 1, 'e-info' => 1, 'tsu' => 1,
                'ccw' => 1, 'lotuslight' => 1, 'godsdirectcontact' => 1, 'taup' => 1, 'tahr' => 1, 'cahr' => 1, 'wufi' => 1, 'greenparty' => 1, 'hi-on' => 1, 'atj' => 1,
                'taiwantt' => 1, 'rti' => 1, 'hwayue' => 1, 'yam' => 1, 'cmi' => 1,
            ),
            'edu' => array(
                'ntu' => 1, 'heeact' => 1,
            ),
            'citytalk' => 1, 'focustaiwan' => 1, 'digiland' => 1, 'twbbs' => 1,
            'club' => array(
                'domain' => 1,
            ),
            'civilmedia' => 1,
            'net' => array(
                'so-net' => 1, 'twbbs' => 1, 'hst' => 1, 'mymusic' => 1, 228 => 1,
            ),
            'amnesty' => 1, 'gov' => 1, 'url' => 1, 'taiwantoday' => 1, '0rz' => 1, 'im88' => 1, 'xianjian' => 1, 'culture' => 1, 'newtalk' => 1, 'sharpdaily' => 1, 'funf' => 1, 'fpmt' => 1,
            'greatroc' => 1, 'taaze' => 1, 'dcard' => 1, 'soh' => 1, 'sitebro' => 1, 'peoplenews' => 1, 'student' => 1, 'uncyclopedia' => 1, 'popo' => 1,
        ),
        'au' => array(
            'com' => array(
                'surfeasy' => 1, 'businessinsider' => 1, 'smh' => 1, 'actimes' => 1, 'tascn' => 1, 'aofriend' => 1, 'newlandmagazine' => 1, 'tibetoffice' => 1, 'chinatown' => 1, 'domaintoday' => 1,
                1688 => 1, 'aobo' => 1, 'oursteps' => 1, 'xxxx' => 1,
            ),
            'id' => array(
                'nf' => 1,
            ),
            'net' => array(
                'radioaustralia' => 1,
            ),
            'org' => array(
                'impact' => 1, 'atc' => 1, 'etaa' => 1, 'tagwa' => 1,
            ),
        ),
        'me' => array(
            'blogcity' => 1, 'twip' => 1, 'emuparadise' => 1, 'zi5' => 1, 'acg18' => 1, 'vpnsecure' => 1, 'line' => 1, 'cdd' => 1, 'tmi' => 1, 'riku' => 1,
            'sogrady' => 1, 'tweeplike' => 1, 'dabr' => 1, 'freewallpaper4' => 1, 'xiaolan' => 1, 'iportal' => 1, 'mangafox' => 1, 'faceless' => 1,
            'zuobiao' => 1, 'klip' => 1, 'baixing' => 1, 'btku' => 1, 'javfor' => 1, 'chinaaid' => 1, 'npnt' => 1, 'seraph' => 1, 'fb' => 1,
            'beric' => 1, 'qi-gong' => 1, 'saiq' => 1, 'vid' => 1, 'hide' => 1,
        ),
        'ir' => array(
            'irib' => 1,
        ),
        'no' => array(
            'nrk' => 1, 'secretgarden' => 1,
        ),
        'edu' => array(
            'usma' => 1, 'westpoint' => 1, 'usc' => 1, 'umich' => 1, 'american' => 1, 'hkcmi' => 1, 'caltech' => 1, 'mit' => 1, 'cgst' => 1, 'stanford' => 1, 'abs' => 1, 'virginia' => 1,
        ),
        'mil' => array(
            'army' => 1, 'dfas' => 1, 'usfk' => 1, 'arlingtoncemetery' => 1, 'soc' => 1, 'dtic' => 1, 'usmc' => 1, 'nga' => 1, 'navy' => 1, 'af' => 1, 'ng' => 1, 'darpa' => 1,
        ),
        'it' => array(
            'uderzo' => 1, 'itsky' => 1, 'justpaste' => 1, 'asianews' => 1, 'oxid' => 1, 'flagsonline' => 1, 'epochtimes' => 1,
        ),
        'tc' => array(
            'wo' => 1,
        ),
        'be' => array(
            'youtu' => 1, 'chinacitynews' => 1, 'lesoir' => 1, 'maruta' => 1, 'ilove80' => 1, 'skynet' => 1,
        ),
        'de' => array(
            'privacybox' => 1, 'xinbao' => 1, 'chinesen' => 1, 'mobileways' => 1, 'nde' => 1, 'bloomberg' => 1, 'dw' => 1, 'trimondi' => 1, 'helpster' => 1, 'prosiben' => 1,
            'jinhai' => 1, 'kaiyuan' => 1, 'otto' => 1, 'desipro' => 1, 'enfal' => 1, 'tibet-initiative' => 1, 'epochtimes' => 1, 'dajiyuan' => 1, 'cineastentreff' => 1, 'tibetgermany' => 1,
            'blog' => 1, 'dw-world' => 1, 'csuchen' => 1, 'dolc' => 1, 'addictedtocoffee' => 1, 'ndr' => 1, 'wikileaks' => 1, 'faluninfo' => 1,
            'i2p2' => 1, 'gfbv' => 1, 'sueddeutsche' => 1, 'twibble' => 1, 'tibet-munich' => 1, 'asianwomensfilm' => 1, 'savetibet' => 1, 'deutsche-welle' => 1,
            'falungong' => 1, 'igmg' => 1, 'clipfish' => 1,
        ),
        'club' => array(
            'tuo8' => 1,
        ),
        'gov' => array(
            'bbg' => 1, 'nasa' => 1, 'cms' => 1, 'cecc' => 1, 'archives' => 1, 'nps' => 1, 'state' => 1, 'uspto' => 1, 'americorps' => 1,
        ),
        'cc' => array(
            'ptt' => 1, 'tiny' => 1, 'sto' => 1, 'sex8' => 1, 'xjp' => 1, 'wretch' => 1, 'uni' => 1, 'raremovie' => 1, 'newspeak' => 1, 'm-team' => 1, 'jbtalks' => 1, 'on' => 1,
            'gaymap' => 1, 'twistar' => 1, 'cz' => 1, 'tuo8' => 1, 'disp' => 1, 'netme' => 1, 'usus' => 1, 'jkb' => 1, 'hacken' => 1, 'taiwanonline' => 1,
            'gobet' => 1, 'ub0' => 1,
        ),
        'info' => array(
            'geekheart' => 1, 'taolun' => 1, 'sinopitt' => 1, 'dalailamaprotesters' => 1, 'weekmag' => 1, '99cn' => 1, 'weiming' => 1, 'kzeng' => 1,
            'chinaworker' => 1, 'lester850' => 1, 'tbpic' => 1, 'thehots' => 1, '2008xianzhang' => 1, 'gongmeng' => 1, 'marc' => 1, 'cdig' => 1, 'magic-net' => 1, 'youxu' => 1,
            'sproxy' => 1, 'vpnuk' => 1, 'caobian' => 1, 'facesoftibetanselfimmolators' => 1, 'vica' => 1, 'xlfmwz' => 1, 'tuitui' => 1, 'fanglizhi' => 1, 'upload4u' => 1, 'fanyue' => 1,
            'soumo' => 1, 'freedomchina' => 1, 'stoneip' => 1, 'gzone-anime' => 1, 'itaboo' => 1, 'hjclub' => 1, '2-hand' => 1, 'proxomitron' => 1, 'wikilivres' => 1, 'laoyang' => 1,
            'istef' => 1, 'spring4u' => 1, 'hizb-ut-tahrir' => 1, 'cellulo' => 1, 'winwhispers' => 1, 'zhenlibu' => 1, 'wepn' => 1, 'dscn' => 1, 'rmjdw132' => 1,
            'dpr' => 1, 'xyy69' => 1, 'faiththedog' => 1, 'say2' => 1, 'falunasia' => 1,
        ),
        'us' => array(
            'foxdie' => 1, 'tangren' => 1, 'thedw' => 1, 'izaobao' => 1, 'devio' => 1, 'aculo' => 1, 'referer' => 1, 'paperb' => 1, 'nobodycanstop' => 1, 'topshare' => 1,
            'imageshack' => 1, 'sis001' => 1, 'chinaaid' => 1, 'tibethouse' => 1, 'dontfilter' => 1, 'freessh' => 1, 'eastturkistangovernmentinexile' => 1,
            'livingonline' => 1, 'huaren' => 1, 'china5000' => 1, 'dit-inc' => 1, 'sadpanda' => 1, 'flgg' => 1, 'untraceable' => 1, 'sitetag' => 1, 'cytode' => 1,
        ),
        'fr' => array(
            'ultravpn' => 1, 'tibetan' => 1, 'savetibet' => 1, 'incredibox' => 1, 'lemonde' => 1, 'iphonix' => 1, 'info-graf' => 1, 'free' => 1, 'epochtimes' => 1,
            'rfi' => 1, 'tibet' => 1, 'agnesb' => 1, 'flecheinthepeche' => 1,
        ),
        'mx' => array(
            'org' => array(
                'casatibet' => 1,
            ),
        ),
        'fm' => array(
            'views' => 1, 'twt' => 1, 'ping' => 1, 'favstar' => 1, 'tweetmylast' => 1, 'date' => 1, 'turntable' => 1,
        ),
        'biz' => array(
            'secretsline' => 1, 'tweetboner' => 1, 'goagent' => 1, 'greatfirewall' => 1, '4bluestones' => 1, 'rangwang' => 1, 'zhenxiang' => 1,
        ),
        'li' => array(
            'htl' => 1, 'owl' => 1, 'hongzhi' => 1, 'paper' => 1,
        ),
        'ca' => array(
            'toptip' => 1, 'londonchinese' => 1, 'city365' => 1, 'hmvdigital' => 1, 'nydus' => 1, '3ren' => 1, 'zhongguo' => 1, 'new96' => 1, 'iask' => 1,
            'leisurecafe' => 1, 'sinomontreal' => 1, 'singtao' => 1, 'qidian' => 1, 'cclife' => 1, 66 => 1, 'ccvoice' => 1, 'ccue' => 1, 'identi' => 1, 'tibet' => 1, 'psiphon' => 1, 'gotw' => 1,
            't88' => 1, 'cbc' => 1, 'kwcg' => 1, 51 => 1, 'easyca' => 1, 'metrolife' => 1, 'aol' => 1, 'peace' => 1, 'yorkbbs' => 1, 'leirentv' => 1, 'naol' => 1, 'calgarychinese' => 1,
            'rcinet' => 1, 'ntdtv' => 1, 'dushi' => 1, 'sinonet' => 1,
        ),
        'how' => array(
            'get' => 1,
        ),
        'in' => array(
            'tuo8' => 1, 'facebook' => 1, 'topnews' => 1, 'bbc' => 1, 'tibetcharity' => 1, 'pixnet' => 1, 'xcafe' => 1, 'xiaod' => 1, 'biantailajiao' => 1, 'teck' => 1,
            'huiyi' => 1, 'avdb' => 1, 'indiandefensenews' => 1, 'gongm' => 1, 'percy' => 1, 'embr' => 1, 'openervpn' => 1, 'wozy' => 1,
        ),
        'es' => array(
            'samsoff' => 1, 'twittertim' => 1, 'lastfm' => 1, 'proxyanonimo' => 1, 'unblocksit' => 1, 'xvideos' => 1, 'xihua' => 1,
        ),
        'ws' => array(
            'top81' => 1, 'localdomain' => 1, 'weisuo' => 1,
        ),
        'io' => array(
            'gitbooks' => 1, 'apiary' => 1,
            'github' => array(
                'onionhacker' => 1, 'wsgzao' => 1, 'cthlo' => 1,
            ),
            'pen' => 1, 'twaud' => 1, 'codeshare' => 1, 'soup' => 1, 'mathable' => 1, 'getmdl' => 1, 'git' => 1,
        ),
        'se' => array(
            'ipredator' => 1, 'epochtimes' => 1, 'tuidang' => 1, 'torrentproject' => 1, 'nyaa' => 1, 'desc' => 1, 'facebook' => 1, 'nobel' => 1,
            'a' => array(
                'tibet' => 1,
            ),
            'dilber' => 1,
        ),
        'nl' => array(
            'trouw' => 1, 'twurl' => 1, 'portablevpn' => 1, 'facebook' => 1, 'uighur' => 1, 'hideme' => 1, 'savetibet' => 1, 'freevpn' => 1,
        ),
        'tv' => array(
            'hotav' => 1, 'avdb' => 1, 'goodtv' => 1, 'ustream' => 1, '1pondo' => 1, 'ntd' => 1, 'muzu' => 1, 'videomega' => 1, 'tibetonline' => 1,
            'jobso' => 1, 'bb-chat' => 1, 'boxun' => 1, 'co' => 1, 'woopie' => 1, 'pandora' => 1, 'blip' => 1, 'avcity' => 1, 'vocn' => 1, 'gzm' => 1,
            'tsquare' => 1, 'azubu' => 1, 'jav68' => 1, 'im' => 1, 'hilive' => 1, 'buddhistchannel' => 1, 'bbchat' => 1, 'azerbaycan' => 1, 'wav' => 1, 'hentaitube' => 1,
        ),
        'to' => array(
            'mash' => 1, 'us' => 1, 'tora' => 1, 'xfiles' => 1, 'moby' => 1, 'uk' => 1, 'hentai' => 1, 'asg' => 1, 'mychat' => 1, 'uploaded' => 1,
        ),
        'tl' => array(
            'bx' => 1, 'twt' => 1, 'mtw' => 1, 'page' => 1,
        ),
        'my' => array(
            'com' => array(
                'orientaldaily' => 1, 'sinchew' => 1, 'cari' => 1, 'kwongwah' => 1, 'chinapress' => 1,
            ),
            'rfi' => 1, 'jbtalks' => 1,
        ),
        'tk' => array(
            'ezpc' => 1, 'tamiaode' => 1,
        ),
        'cm' => array(
            'fw' => 1,
        ),
        'mn' => array(
            'impp' => 1, 'dalailama' => 1,
        ),
        'ru' => array(
            'com' => array(
                'a5' => 1,
            ),
            'pp' => array(
                'xfm' => 1, 'abc' => 1, 'heix' => 1,
            ),
            'ipicture' => 1, 'clinica-tibet' => 1, 'hut2' => 1, 'ntdtv' => 1, 'epochtimes' => 1, 'fastpic' => 1, 'rutube' => 1,
            'narod' => 1, 'gigporno' => 1, 'manicur4ik' => 1, 'dalailama' => 1, 'savetibet' => 1, 'samair' => 1, 'mail' => 1,
        ),
        'gd' => array(
            'is' => 1, 'tl' => 1,
        ),
        'im' => array(
            'elgoog' => 1, 'esu' => 1, 'wzyboy' => 1, 'ff' => 1, 'kun' => 1, 'cao' => 1,
        ),
        'xxx' => array(
            'catfightpayperview' => 1, 'sis' => 1,
        ),
        'name' => array(
            'psblog' => 1, 'kui' => 1,
        ),
        'ch' => array(
            'mad-ar' => 1, 'wikileaks' => 1, 'wenhui' => 1, 'lematin' => 1, 'tibetoffice' => 1,
        ),
        'pl' => array(
            'wikileaks' => 1,
        ),
        'nu' => array(
            'bot' => 1, 'tibet' => 1,
        ),
        'co' => array(
            'decodet' => 1, 'cochina' => 1, 't' => 1,
            'net' => array(
                'twister' => 1,
            ),
            'g' => 1, 'allconnected' => 1, 'bbc' => 1,
        ),
        'cn' => array(
            'gmbd' => 1, 'xh4n' => 1, 'zhuanxing' => 1, 'vanemu' => 1, 'kissbbao' => 1, 'keso' => 1, 'sjum' => 1, 'daxa' => 1, 'qixianglu' => 1,
            'google' => 1, 'zmw' => 1, 'edmontonchina' => 1, 'bloomberg' => 1, 'syx86' => 1,
        ),
        'asia' => array(
            'bod' => 1, 'idemocracy' => 1, 'cantonese' => 1,
        ),
        'tt' => array(
            'db' => 1, 'ift' => 1,
        ),
        'do' => array(
            'bit' => 1,
        ),
        'cz' => array(
            'epochtimes' => 1, 'ntdtv' => 1, 'jiehua' => 1,
        ),
        'bz' => array(
            'iask' => 1,
        ),
        'at' => array(
            'spem' => 1, 'tibet' => 1, 'fffff' => 1,
        ),
        'is' => array(
            'archive' => 1,
        ),
        'hu' => array(
            'yong' => 1, 'facebook' => 1,
        ),
        'uk' => array(
            'org' => 1, 'com' => 1, 'co' => 1,
        ),
        'br' => array(
            'com' => array(
                'centauro' => 1,
            ),
            'facebook' => 1,
        ),
        'sk' => array(
            'velkaepocha' => 1,
        ),
        'wang' => array(
            'hasi' => 1,
        ),
        'lu' => array(
            'qiwen' => 1, 'wikileaks' => 1,
        ),
        'ly' => array(
            'ow' => 1, 'list' => 1, 'ht' => 1, 'img' => 1, 'bit' => 1, 'deck' => 1, 'cl' => 1,
        ),
        'xyz' => array(
            'abc' => 1, 'javmoo' => 1, 'shadowsky' => 1,
        ),
        'la' => array(
            'zuo' => 1,
        ),
        'su' => array(
            'hec' => 1, 'marguerite' => 1, 'arethusa' => 1,
        ),
        'ml' => array(
            'sspro' => 1, 'wowlegacy' => 1,
        ),
        'mobi' => array(
            'shkspr' => 1, 'wapedia' => 1, 'voa' => 1, 'dabr' => 1,
        ),
        'pw' => array(
            'tuo8' => 1, 'avmoo' => 1, 'avmo' => 1,
        ),
        'cr' => array(
            'kat' => 1,
        ),
        'ma' => array(
            'shadow' => 1,
        ),
        'ms' => array(
            'nyti' => 1,
        ),
        'id' => array(
            'web' => array(
                'hudatoriq' => 1,
            ),
            'or' => array(
                'pemulihan' => 1,
            ),
        ),
        'ie' => array(
            'epochtimes' => 1,
        ),
        'mg' => array(
            'storm' => 1,
        ),
        'ee' => array(
            'mcaf' => 1,
        ),
        'ua' => array(
            'org' => array(
                'gfw' => 1,
            ),
        ),
        'dk' => array(
            'tibetcharity' => 1,
        ),
        'mp' => array(
            'j' => 1,
        ),
        'ph' => array(
            'huaxin' => 1,
        ),
        'gl' => array(
            'goo' => 1,
        ),
        'ninja' => array(
            'tuo8' => 1,
        ),
        'gg' => array(
            'ra' => 1,
        ),
        'st' => array(
            'br' => 1,
        ),
        'kz' => array(
            'kiwi' => 1,
        ),
        'soy' => array(
            'iam' => 1,
        ),
        'ar' => array(
            'com' => array(
                'free4u' => 1,
            ),
        ),
    );
    
    public static function getDomains(){
        return self::$domain;
    }
    
    
    
}
