<?php

/**
 * Created by IntelliJ IDEA.
 * User: lidc
 * Date: 17-12-22
 * Time: 下午2:05
 */
class Controller_About extends Admin
{
    protected $model_about;
    protected $layout = 'base';

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        $this->model_about = new Model_About();
    }

    /**
     * 列表
     * */
    public function listAction()
    {
        $list = $this->model_about->aboutList($this->_request->getQuery());
        $this->assign('list', $list);
        $this->display("about/list");
    }

    /**
     * 状态修改
     * */
    public function editAction()
    {
        if ($this->_request->isPost()) {
            $re = $this->model_about->aboutEdit($this->_request->getPost());
            if ($re['ret'] == 1) fn_ajax_return(1, '修改成功');
            fn_ajax_return(0, '修改失败');
        }
    }

}