<?php

/**
 * Created by IntelliJ IDEA.
 * User: lidc
 * Date: 17-12-6
 * Time: 下午3:18
 * 广告管理
 */
class Controller_Advert extends Admin
{
    private $model_advert;
    protected $layout = 'base';
    private $model_user;

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        $this->model_advert = new Model_Advert();
        $this->model_user = new Model_User();
    }

    /**
     * h5广告列表
     * */
    public function advertH5ListAction()
    {
        $list = $this->model_advert->advertList($this->_request->getQuery());
        $this->assign('list', $list);
        $this->display("advert/list");
    }


    /**
     * h5广告新建
     * */
    public function advertH5CreateAction()
    {

        if ($this->_request->isPost()) {
            $re = $this->model_advert->advertH5Create($this->_request->getPost());
            if ($re['ret'] == 1) fn_ajax_return(1, $re['msg']);
            fn_ajax_return(0, $re['msg']);
        }
        $userList = $this->model_advert->select(['id', 'user_name'], ['status' => 0]);
        $this->assign('user', $userList);
        $this->display("advert/create");
    }

    /**
     *  删除
     * */
    public function delAdvertAction()
    {
        $re = $this->model_advert->advertDel($this->_request->getPost());
        if ($re['ret'] == 1) fn_ajax_return(1, '删除成功');
        fn_ajax_return(0, '删除失败');
    }

    /**
     * 编辑
     * */
    public function editAction()
    {
        if ($this->_request->isPost()) {
            $re = $this->user->advertH5Create($this->_request->getPost());
            if ($re['ret'] == 1) fn_ajax_return(1, $re['msg']);
            fn_ajax_return(0, $re['msg']);
        }
        $data = $this->_request->getQuery();
//        $userList = $this->model_user->select(['id', 'user_name'], ['status' => 0]);
//        $this->assign('user', $userList);
        if (isset($data['id']) && $data['id']) {
            $field = ['id', 'user_id', 'ad_name', 'ad_type', 'business_type', 'put_day_limit', 'put_begin_date', 'put_end_date',
                'put_time_point', 'put_pic', 'put_pic_thumb', 'put_click_url', 'put_price', 'put_onoff', 'weight', 'put_btn_title', 'create_time', 'adinfo_expire_date'
            ];
            $info = $this->model_advert->get($field, ['id' => $data['id']]);
            $this->assign('info', $info);
            $this->display("advert/create");
        } else {
            $this->display("advert/create");
        }
    }

    /**
     * js广告列表
     * */
    public function advertJsListAction()
    {
        $list = $this->model_advert->advertList($this->_request->getPost());
        $this->assign('list', $list);
        $this->display("advert/list");
    }

    /**
     * js广告新建
     * */
    public function advertJsCreateAction()
    {
        $re = $this->model_advert->advertJsCreate($this->_request->getPost());
        if ($re['re'] == 1) fn_ajax_return(1, '创建成功');
        fn_ajax_return(0, $re['msg']);
    }


}