<?php

/**
 * Created by IntelliJ IDEA.
 * User: lidc
 * Date: 17-12-5
 * Time: 下午3:30
 */
class Controller_User extends Admin
{
    private $user;
    protected $layout = 'base';

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        $this->user = new Model_User();
    }

    /**
     * 网站主列表
     * */
    public function listAction()
    {
        $list = $this->user->listData($this->_request->getQuery());
        $this->assign('list',$list);
        $this->display('user/list');
    }

    /**
     * 新建网站主账号
     * */
    public function createAction()
    {
        if($this->_request->isPost()){
            $re = $this->user->createUser($this->_request->getPost());
            if ($re['ret'] == 1) fn_ajax_return(1, $re['msg']);
            fn_ajax_return(0, $re['msg']);
        }
        $this->display("user/create");
    }

    /**
     * 编辑
     * */
    public function editAction()
    {
        if($this->_request->isPost()){
            $re = $this->user->createUser($this->_request->getPost());
            if ($re['ret'] == 1) fn_ajax_return(1, $re['msg']);
            fn_ajax_return(0, $re['msg']);
        }
        $data = $this->_request->getQuery();
        if(!isset($data['id']) && !$data['id'] && !is_numeric($data['id'])){
            Header("Location: /admin/member/login");
        }
        $info = $this->user->get(['id','user_name','phone','email','qq'],['id'=>$data['id']]);
        $this->assign('info',$info);
        $this->display("user/create");
    }

    /**
     * 冻结/解冻/删除
     * */
    public function frozenUserAction()
    {
        $re = $this->user->frozenUser($this->_request->getPost());
        if ($re['ret'] == 1) fn_ajax_return(1, $re['msg']);
        fn_ajax_return(0, $re['msg']);
    }

    /**
     * 重置密码
     * */
    public function resetPswAction()
    {
        $re = $this->user->resetPsw($this->_request->getPost());
        if ($re['ret'] == 1) fn_ajax_return(1, $re['msg']);
        fn_ajax_return(0, $re['msg']);
    }
}