<?php

/**
 * Created by IntelliJ IDEA.
 * User: lidc
 * Date: 17-12-22
 * Time: 下午2:05
 */
class Controller_About extends Web
{
    private $model_about;
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        $this->model_about = new Model_About();
    }

    public function aboutAction()
    {
        if($this->_request->isPost()){
            $re = $this->model_about->aboutAdd($this->_request->getPost());
            if ($re['ret']) fn_ajax_return(1, '预约成功');
            fn_ajax_return(0, $re['msg']);
        }
        fn_ajax_return(0, '参数错误');
    }
}